"""
Prompt di base per l'OCR Avanzato, divisi per tipologia documentale.
Ogni tipo fornisce linee guida paleografiche specifiche all'IA.
"""


def get_available_types():
    return [
        # ── Stato Civile Napoleonico (SCN, 1806-1815) ──────────────────────────
        "SCN — Atto di Nascita (1806-1815)",
        "SCN — Atto di Matrimonio (1806-1815)",
        "SCN — Atto di Morte (1806-1815)",
        # ── Stato Civile della Restaurazione (SCR, 1815-1865) ─────────────────
        "SCR — Atto di Nascita (1815-1865)",
        "SCR — Atto di Matrimonio (1815-1865)",
        "SCR — Atto di Morte (1815-1865)",
        # ── SCR — varianti regionali ───────────────────────────────────────────
        "SCR/Toscana — Atto di Nascita (1817-1865)",
        "SCR/Toscana — Atto di Matrimonio (1817-1865)",
        "SCR/Toscana — Atto di Morte (1817-1865)",
        "SCR/Due Sicilie — Atto di Nascita (1816-1865)",
        "SCR/Due Sicilie — Atto di Matrimonio (1816-1865)",
        "SCR/Due Sicilie — Atto di Morte (1816-1865)",
        "SCR/Piemonte — Atto di Nascita (1837-1865)",
        "SCR/Piemonte — Atto di Matrimonio (1837-1865)",
        "SCR/Piemonte — Atto di Morte (1837-1865)",
        # ── Stato Civile Italiano (SCI, dal 1866) ─────────────────────────────
        "SCI — Atto di Nascita (dal 1866)",
        "SCI — Atto di Matrimonio (dal 1866)",
        "SCI — Atto di Morte (dal 1866)",
        # ── Periodo incerto / generico ─────────────────────────────────────────
        "Atto di Stato Civile (Nascita / Battesimo)",
        "Atto di Stato Civile (Matrimonio)",
        "Atto di Stato Civile (Morte / Sepoltura)",
        "Processetto / Allegati Matrimoniali",
        "Stati delle Anime Granducato di Toscana",
        "Stato delle Anime / Censimento Parrocchiale",
        "Censimento Storico (Generico)",
        "Indice / Registro degli Atti",
        "Documento Notarile",
        "Atto in Latino Ecclesiastico",
        "Lettera / Corrispondenza Privata",
        "Testo a Stampa Antico",
        "Documento Generico / Non Classificato",
    ]


def compose_ocr_prompt(doc_type, user_instructions="", example_text=""):
    """
    Costruisce il prompt per la trascrizione paleografica in base alla tipologia.
    """
    base = (
        "Sei un esperto paleografo con specializzazione in documenti storici italiani.\n"
        "COMPITO: Trascrivi FEDELMENTE il testo contenuto nell'immagine.\n\n"
        "REGOLE ASSOLUTE:\n"
        "1. Non normalizzare nomi propri, cognomi o termini dialettali: trascrivili esattamente come scritti.\n"
        "2. Mantieni la disposizione del testo originale (a capo, paragrafi, colonne).\n"
        "3. Indica le letture incerte con [?] immediatamente dopo la parola dubia.\n"
        "4. Sciogli le abbreviazioni ovvie tra parentesi angolate < >.\n"
        "5. Non aggiungere commenti, titoli o note a margine: solo il testo trascritto.\n"
    )

    type_specific = {
        # ── SCN: Stato Civile Napoleonico (1806-1815) ──────────────────────────
        "SCN — Atto di Nascita (1806-1815)": (
            "\nTIPOLOGIA: Atto di nascita dello Stato Civile Napoleonico (SCN, 1806-1815).\n"
            "Il SCN fu introdotto con il Codice Civile francese e redatto dagli ufficiali comunali"
            " (sindaco o delegato), NON dai parroci.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno in lettere ('L'anno milleottocentosei'), giorno e mese in lettere,"
            " nome del comune, nome e qualifica dell'ufficiale di stato civile.\n"
            "- Comparente: il padre (o, in sua assenza, due testimoni adulti maschi) che 'presenta'"
            " il neonato fisicamente all'ufficiale. Dati: nome, cognome, età, professione, domicilio.\n"
            "- Neonato: sesso ('di sesso maschile/femminile'), nome imposto, data e ora di nascita.\n"
            "- Due testimoni maschi maggiorenni: nome, cognome, età, professione, domicilio.\n"
            "- Formula di chiusura: lettura dell'atto, firme del dichiarante e dei testimoni"
            " (o croce/nota 'ha dichiarato di non saper firmare'), firma dell'ufficiale.\n"
            "- N° atto: in genere nel margine sinistro o nell'intestazione.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date sono in lettere: 'il giorno tre maggio milleottocentosei'.\n"
            "- Il termine 'fu' indica genitore defunto: trascrivilo letteralmente.\n"
            "- Abbreviazioni frequenti: Gio. = Giovanni, Batta. = Battista, Fran.co = Francesco.\n"
            "- MARGINALIA: trascrivi annotazioni a margine con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCN — Atto di Matrimonio (1806-1815)": (
            "\nTIPOLOGIA: Atto di matrimonio dello Stato Civile Napoleonico (SCN, 1806-1815).\n"
            "Redatto dall'ufficiale di stato civile comunale, preceduto da tre pubblicazioni (bandi).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, giorno, mese in lettere; comune; nome dell'ufficiale.\n"
            "- Sposo: nome, cognome, età, professione, domicilio, stato civile (celibe/vedovo);"
            " nome del padre (con 'fu' se defunto) e della madre.\n"
            "- Sposa: stesse informazioni dello sposo; cognome da nubile della madre.\n"
            "- Consensi parentali: se uno degli sposi è minorenne, sono riportati i consensi"
            " dei genitori (o, se defunti, del consiglio di famiglia).\n"
            "- Dichiarazione di volontà: formula 'Dichiaro di voler prendere per mio/a sposo/a'"
            " o equivalente; risposta dell'altro sposo.\n"
            "- Proclamazione dell'ufficiale: formula 'In nome della legge dichiaro uniti in matrimonio'.\n"
            "- Quattro testimoni maschi maggiorenni: nome, cognome, età, professione, domicilio.\n"
            "- Firme degli sposi, dei testimoni, dell'ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date sono in lettere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Le pubblicazioni precedono l'atto e vanno trascritte separatamente con [PUBBLICAZIONE N:].\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCN — Atto di Morte (1806-1815)": (
            "\nTIPOLOGIA: Atto di morte dello Stato Civile Napoleonico (SCN, 1806-1815).\n"
            "Redatto dall'ufficiale di stato civile comunale su dichiarazione di due testimoni.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, giorno, mese in lettere; comune; nome dell'ufficiale.\n"
            "- Due dichiaranti (spesso vicini di casa, parenti o colleghi del defunto):"
            " nome, cognome, età, professione, domicilio e loro qualifica di conoscenza.\n"
            "- Defunto: nome, cognome, età (o data di nascita), professione, domicilio,"
            " stato civile (celibe/coniugato/vedovo), nome del coniuge se coniugato,"
            " nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora e luogo del decesso.\n"
            "- Firme dei dichiaranti (o nota di analfabetismo), firma dell'ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date sono in lettere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Presta attenzione ai termini arcaici per le cause di morte (se indicate).\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR: Stato Civile della Restaurazione (1815-1865) ─────────────────
        "SCR — Atto di Nascita (1815-1865)": (
            "\nTIPOLOGIA: Atto di nascita dello Stato Civile della Restaurazione (SCR, 1815-1865).\n"
            "Dopo il 1815, ogni Stato pre-unitario adottò un sistema proprio. Il formato varia"
            " significativamente per area geografica:\n"
            "- Granducato di Toscana (dal 1817): compilato dal parroco con duplice copia all'Ufficio"
            " dello Stato Civile di Firenze; struttura simile al SCN ma con formule miste civili"
            " ed ecclesiastiche.\n"
            "- Regno delle Due Sicilie (dal 1816) e Sicilia (dal 1820): formula simile al SCN.\n"
            "- Ducato di Modena e Reggio: mantenne il sistema napoleonico quasi invariato.\n"
            "- Regno di Sardegna (dal 1837): formato ibrido piemontese.\n"
            "\nELEMENTI COMUNI A TUTTE LE VARIANTI:\n"
            "- Intestazione con anno, data, comune, ufficiale o parroco.\n"
            "- Comparente (padre o suoi delegati) che presenta il neonato.\n"
            "- Sesso, nome e data di nascita del neonato.\n"
            "- Nomi dei genitori e almeno un avo (con 'fu' se defunti).\n"
            "- Due o più testimoni con dati anagrafici.\n"
            "- Firme o note di analfabetismo, firma del redattore.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date possono essere in lettere o in cifre a seconda del sistema locale.\n"
            "- 'Fu' (o 'quondam'/'q.m' nei testi latini) indica genitore defunto.\n"
            "- In Toscana frequenti formule religiose anche negli atti civili.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR — Atto di Matrimonio (1815-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio dello Stato Civile della Restaurazione (SCR, 1815-1865).\n"
            "Il formato varia per area geografica (vedi SCR-Nascita per le varianti regionali).\n"
            "\nELEMENTI COMUNI:\n"
            "- Intestazione con anno, data, comune, ufficiale o parroco officiante.\n"
            "- Sposo e sposa con dati anagrafici completi (nome, cognome, età, professione,"
            " domicilio, stato civile, nome dei genitori con 'fu' se defunti).\n"
            "- Consensi parentali o del consiglio di famiglia per i minorenni.\n"
            "- Pubblicazioni (bandi) precedenti: spesso richiamati nell'atto con date e luoghi.\n"
            "- Dichiarazione di volontà di entrambi gli sposi.\n"
            "- Testimoni (due o quattro a seconda del sistema) con dati anagrafici.\n"
            "- In Toscana: possibile presenza di formule religiose e riferimenti al diritto canonico"
            " nell'atto civile.\n"
            "- Firme degli sposi, dei testimoni, dell'ufficiale o parroco.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date possono essere in lettere o in cifre.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR — Atto di Morte (1815-1865)": (
            "\nTIPOLOGIA: Atto di morte dello Stato Civile della Restaurazione (SCR, 1815-1865).\n"
            "Il formato varia per area geografica (vedi SCR-Nascita per le varianti regionali).\n"
            "\nELEMENTI COMUNI:\n"
            "- Intestazione con anno, data, comune, ufficiale o parroco.\n"
            "- Due dichiaranti con dati anagrafici e relazione col defunto.\n"
            "- Defunto: nome, cognome, età, professione, domicilio, stato civile,"
            " nome del coniuge se coniugato o vedovo, nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora (a volte) e luogo del decesso.\n"
            "- Causa di morte: quando indicata, usa terminologia arcaica o dialettale.\n"
            "- Firme o note di analfabetismo, firma del redattore.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- In Toscana frequenti formule religiose (es. 'munito dei SS. Sacramenti').\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR/Toscana (Granducato, 1817-1865) ───────────────────────────────
        "SCR/Toscana — Atto di Nascita (1817-1865)": (
            "\nTIPOLOGIA: Atto di nascita del Granducato di Toscana (SCR/Toscana, 1817-1865).\n"
            "Regolato dalla legge toscana sullo stato civile del 1817. L'ufficiale è il PARROCO\n"
            "della parrocchia, nominato delegato dello Stato. L'atto ha doppia natura\n"
            "civile-ecclesiastica ed è compilato in DOPPIO ORIGINALE: uno conservato in parrocchia,\n"
            "uno inviato all'Ufficio di Stato Civile di Firenze.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno in cifre arabiche, giorno e mese, nome della parrocchia,"
            " nome e titolo del sacerdote-ufficiale ('io sottoscritto Sacerdote N.N. Parroco di...').\n"
            "- Comparente: di norma il padre, comparso 'avanti di me'; nome, cognome, età,"
            " professione, domicilio.\n"
            "- Neonato: sesso, nome imposto, data e ora di nascita.\n"
            "- Battesimo: spesso indicato nell'atto stesso ('da me battezzato il giorno...' o"
            " 'battezzato nella stessa giornata'): trascrivilo per intero.\n"
            "- Padre e madre: nome, cognome da nubile della madre, stato civile, professione,"
            " domicilio.\n"
            "- Due testimoni: nome, cognome, età, professione, parrocchiani noti al sacerdote.\n"
            "- Formula di chiusura con elementi ecclesiastici intercalati.\n"
            "- Firma del sacerdote-parroco con titolo; N° atto in margine o intestazione.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- L'anno è in cifre arabiche (differenza rispetto al SCN).\n"
            "- Formule religiose intercalate nel testo civile: trascrivile per intero.\n"
            "- Il riferimento al battesimo è strutturale: se presente, trascrivilo.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Script: corsivo toscano ottocentesco; cancelleresca residua nei registri ante 1830.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Toscana — Atto di Matrimonio (1817-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio del Granducato di Toscana (SCR/Toscana, 1817-1865).\n"
            "Il parroco svolge il triplice ruolo di ministro del sacramento, ufficiale dello stato"
            " civile e testimone istituzionale. L'atto civile e il verbale canonico quasi coincidono.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, parrocchia, nome del sacerdote-ufficiale.\n"
            "- Tre pubblicazioni (bandi): elencate con date domenicali; talvolta riportate\n"
            "  nell'atto stesso, talvolta come documento separato allegato.\n"
            "- Sposo: nome, cognome, età, professione, domicilio, stato civile (celibe/vedovo),"
            " padre e madre (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile.\n"
            "- Consensi parentali se minorenni (uomini sotto 25 anni, donne sotto 21).\n"
            "- Dichiarazione di volontà di entrambi gli sposi.\n"
            "- Almeno due testimoni, spesso quattro; dati anagrafici completi.\n"
            "- Formula di chiusura mista canonica e civile: trascrivila per intero.\n"
            "- Firme degli sposi (o croci), testimoni, sacerdote-ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Formule latine canoniche possono essere intercalate nel testo italiano.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Toscana — Atto di Morte (1817-1865)": (
            "\nTIPOLOGIA: Atto di morte del Granducato di Toscana (SCR/Toscana, 1817-1865).\n"
            "Compilato dal parroco come ufficiale delegato. Spesso include anche la registrazione\n"
            "della sepoltura (luogo e data).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, parrocchia, sacerdote-ufficiale.\n"
            "- Due dichiaranti (di norma vicini o parenti): nome, cognome, età, professione,"
            " relazione col defunto.\n"
            "- Defunto: nome, cognome, età, professione, domicilio, stato civile,"
            " nome del coniuge superstite (o 'vedovo/vedova di'), nomi dei genitori (con 'fu').\n"
            "- Data, ora e luogo del decesso.\n"
            "- Causa di morte: spesso con terminologia arcaica o religiosa ('vizio di petto',"
            " 'accidente apoplettico', 'munito dei SS. Sacramenti').\n"
            "- Note di sepoltura: luogo (chiesa, camposanto), data, sacramenti ricevuti.\n"
            "- Firme o croci dei dichiaranti, firma del sacerdote-ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Munito dei SS. Sacramenti' o formule simili: trascrivi per intero.\n"
            "- Cause di morte in terminologia arcaica: non correggere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR/Due Sicilie (Regno delle Due Sicilie, 1816-1865) ───────────────
        "SCR/Due Sicilie — Atto di Nascita (1816-1865)": (
            "\nTIPOLOGIA: Atto di nascita del Regno delle Due Sicilie (SCR/Due Sicilie,"
            " 1816-1865; Sicilia dal 1820).\n"
            "Istituito da Ferdinando I. L'ufficiale è il SINDACO DECURIONALE (o delegato),"
            " figura tipica dell'amministrazione borbonica.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, 'avanti di me Sindaco del Comune di... /"
            " Ufficiale dello Stato Civile', nome del sindaco o delegato.\n"
            "- Comparente: il padre; formula tipica: 'è comparso N.N. di anni X, di professione"
            " Y, domiciliato in...'.\n"
            "- Neonato: sesso, nome, data e ora di nascita, luogo.\n"
            "- 'Figlio legittimo di' [padre] e di [madre con cognome da nubile].\n"
            "- Madre: nome, cognome da nubile, età, professione, domicilio.\n"
            "- Due testimoni maschi con dati anagrafici completi.\n"
            "- Formula di chiusura e firme.\n"
            "\nPARTICOLARITÀ DEL SISTEMA BORBONICO:\n"
            "- L'ufficio è detto 'Decurionato' (non 'Municipio'): trascrivilo esattamente.\n"
            "- L'ufficiale può essere 'il Sindaco', 'il Vice-Sindaco' o 'l'Eletto al quartiere'.\n"
            "- Formula 'di anni X' per l'età (non solo la cifra come nel SCN).\n"
            "- Sicilia: cognomi e nomi spesso in forma dialettale siciliana (es. 'Ncolò',"
            " 'Agustinu', 'Salvaturi'): non correggere, trascrivili esattamente.\n"
            "- Dialettalismi in cognomi calabresi, pugliesi, campani: trascrivi esattamente.\n"
            "- Script: corsivo meridionale; tratti barocchi nei registri anteriori al 1840.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Due Sicilie — Atto di Matrimonio (1816-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio del Regno delle Due Sicilie (SCR/Due Sicilie, 1816-1865).\n"
            "L'atto civile è separato dal canonico ma celebrato di norma lo stesso giorno."
            " Il Sindaco Decurionale presiede la cerimonia civile.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Sindaco Decurionale o delegato.\n"
            "- Tre pubblicazioni: citate con date e luoghi; formula 'fatte le tre debite pubblicazioni'.\n"
            "- Sposo: nome, cognome, età ('di anni X'), professione, domicilio, stato civile,"
            " padre e madre (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile.\n"
            "- Dichiarazione di volontà: formula 'dichiara di voler prendere in moglie / marito'.\n"
            "- QUATTRO testimoni (a differenza del SCN che ne richiedeva due): dati anagrafici.\n"
            "- Formula di proclamazione del sindaco.\n"
            "- Firme o croci degli sposi, dei quattro testimoni, del sindaco.\n"
            "\nPARTICOLARITÀ:\n"
            "- 'Decurionato' come termine istituzionale: trascrivilo esattamente.\n"
            "- Quattro testimoni: caratteristica borbonica, diversa dal SCN (due testimoni).\n"
            "- Dialettalismi nei nomi e cognomi: non correggere.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Due Sicilie — Atto di Morte (1816-1865)": (
            "\nTIPOLOGIA: Atto di morte del Regno delle Due Sicilie (SCR/Due Sicilie, 1816-1865).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Sindaco Decurionale o delegato.\n"
            "- Due dichiaranti: nome, cognome, età, professione, relazione col defunto.\n"
            "- Defunto: nome, cognome, età ('di anni X'), professione, domicilio, stato civile,"
            " nome del coniuge se coniugato/vedovo, nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora e luogo del decesso.\n"
            "- Causa di morte: frequentemente in terminologia arcaica e/o dialettale meridionale\n"
            "  ('febbre nervina', 'mal di petto', 'mal di cuore', 'colpo apoplettico', 'tisì').\n"
            "- Note religiose: 'munito dei sacramenti', 'senza sacramenti per morte improvvisa'.\n"
            "- Firme o croci dei dichiaranti, firma del sindaco.\n"
            "\nPARTICOLARITÀ:\n"
            "- 'Decurionato' come termine istituzionale: trascrivilo esattamente.\n"
            "- Cause di morte in dialetto meridionale o siciliano: non correggere, trascrivi letteralmente.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR/Piemonte (Regno di Sardegna — Codice Albertino, 1837-1865) ────
        "SCR/Piemonte — Atto di Nascita (1837-1865)": (
            "\nTIPOLOGIA: Atto di nascita del Regno di Sardegna — Codice Albertino"
            " (SCR/Piemonte, 1837-1865).\n"
            "Istituito con le Regie Patenti del 20 aprile 1837. Applicato in Piemonte, Liguria,"
            " Sardegna (isola) e, dal 1848, nei territori progressivamente annessi.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, 'avanti di me Ufficiale dello Stato Civile del"
            " Comune di...', nome dell'ufficiale (di norma il Sindaco o un consigliere delegato).\n"
            "- Formula di apertura formale e burocratica: 'Il sottoscritto Ufficiale dello Stato"
            " Civile...' o 'Noi sottoscritto...'.\n"
            "- Comparente: il padre; nome, cognome, età, professione, domicilio.\n"
            "- Neonato: sesso, nome, data e ora di nascita; 'figlio legittimo di'.\n"
            "- Padre e madre: dati completi.\n"
            "- Due testimoni con dati completi.\n"
            "- Formula di chiusura e firme.\n"
            "\nPARTICOLARITÀ DELL'AREA SABAUDA:\n"
            "- Alcuni atti sono in FRANCESE o bilingui italiano/francese (Savoia, Valle d'Aosta,"
            " Nizza fino al 1860): trascrivili nella lingua d'origine senza tradurre.\n"
            "- L'anno è in cifre arabiche.\n"
            "- Linguaggio molto burocratico e standardizzato.\n"
            "- Eventuale citazione di 'art. X del Codice Civile Albertino'.\n"
            "- Il modello albertino 1848-1865 è il precursore diretto del SCI.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Se il testo è in francese, trascrivilo in francese senza tradurre.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Piemonte — Atto di Matrimonio (1837-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio del Regno di Sardegna — Codice Albertino"
            " (SCR/Piemonte, 1837-1865).\n"
            "Il matrimonio civile è separato dal canonico. Il Codice Albertino richiedeva"
            " la preventiva pubblicazione dei bandi e il consenso parentale per i minorenni\n"
            "(uomini sotto 25 anni, donne sotto 21).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Ufficiale dello Stato Civile.\n"
            "- Dichiarazione delle pubblicazioni (bandi): date e luoghi.\n"
            "- Sposo: nome, cognome, età, professione, domicilio, stato civile, padre e madre"
            " (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile della madre.\n"
            "- Consensi parentali (atto separato richiamato) o dispense.\n"
            "- Dichiarazione di volontà di ciascuno sposo.\n"
            "- DUE testimoni (a differenza del SCI che ne richiedeva quattro).\n"
            "- Formula di proclamazione dell'ufficiale e firme.\n"
            "\nPARTICOLARITÀ:\n"
            "- Possibile redazione in francese o bilingue: trascrivere nella lingua d'origine.\n"
            "- Eventuale riferimento al numero atto di nascita degli sposi.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Se il testo è in francese, trascrivilo in francese senza tradurre.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Piemonte — Atto di Morte (1837-1865)": (
            "\nTIPOLOGIA: Atto di morte del Regno di Sardegna — Codice Albertino"
            " (SCR/Piemonte, 1837-1865).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Ufficiale dello Stato Civile.\n"
            "- Due dichiaranti con dati anagrafici e relazione col defunto.\n"
            "- Defunto: nome, cognome, età, professione, domicilio, stato civile, nome del coniuge"
            " (cognome da nubile per le donne), nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora e luogo del decesso.\n"
            "- Causa di morte: terminologia medica relativamente moderna rispetto agli altri SCR"
            " (influenza del modello piemontese-francese); in alcune zone ancora terminologia popolare.\n"
            "  Es.: 'polmonite', 'febbre tifoide', 'colera morbus', 'congestione cerebrale'.\n"
            "- Firme o croci dei dichiaranti, firma dell'ufficiale.\n"
            "\nPARTICOLARITÀ:\n"
            "- Possibile redazione in francese o bilingue (Savoia, Nizza): trascrivere nella"
            " lingua d'origine.\n"
            "- Linguaggio burocratico standardizzato.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Se il testo è in francese, trascrivilo in francese senza tradurre.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCI: Stato Civile Italiano (dal 1° gennaio 1866) ──────────────────
        "SCI — Atto di Nascita (dal 1866)": (
            "\nTIPOLOGIA: Atto di nascita dello Stato Civile Italiano (SCI, R.D. 15/11/1865,"
            " in vigore dal 1/1/1866).\n"
            "Formato standardizzato e prestampato, redatto dall'ufficiale di stato civile comunale.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione prestampata: N° atto (nell'intestazione), anno, comune, ufficiale.\n"
            "- Formula fissa: 'L'anno milleottocento..., addì... del mese di..., avanti di me...'\n"
            "- Dichiarante: il padre o un altro comparente; nome, cognome, età, professione, domicilio.\n"
            "- Nascita: luogo esatto (via, casa), data e ora, sesso del neonato ('di sesso maschile/femminile').\n"
            "- Nome imposto al neonato.\n"
            "- Madre: nome, cognome (da nubile), età, professione, domicilio.\n"
            "- Padre: nome, cognome, età, professione, domicilio.\n"
            "- Due testimoni maschi maggiorenni: nome, cognome, età, professione, domicilio.\n"
            "- Formula di chiusura e firme: dichiarante, testimoni, ufficiale.\n"
            "- Dal 1875: possibili annotazioni a margine (matrimoni futuri, morte, note).\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il N° atto è in cifre arabiche: trascrivilo con precisione.\n"
            "- Le date dell'anno sono in lettere; giorno e mese possono essere in cifre o lettere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA (frequenti nel SCI): trascrivi tutte le annotazioni a margine"
            " con il tag [MARGINE: ...]; contengono spesso riferimenti a matrimonio, morte,"
            " riconoscimento di paternità — informazioni preziose.\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCI — Atto di Matrimonio (dal 1866)": (
            "\nTIPOLOGIA: Atto di matrimonio dello Stato Civile Italiano (SCI, dal 1/1/1866).\n"
            "Formato standardizzato prestampato. Nel SCI il matrimonio comprende tre fasi documentali:\n"
            "1) Pubblicazioni (richiesta preventiva, tre domeniche consecutive);\n"
            "2) Atto di matrimonio vero e proprio;\n"
            "3) Eventuali allegati (estratti di nascita, consensi, dispense).\n"
            "\nSTRUTTURA DELL'ATTO DI MATRIMONIO:\n"
            "- Intestazione: N° atto, anno, comune, ufficiale di stato civile.\n"
            "- Formula fissa: 'L'anno... avanti di me... si sono presentati...'\n"
            "- Sposo: nome, cognome, luogo e data di nascita (o età), professione, domicilio,"
            " stato civile (celibe/vedovo), nome del padre e della madre (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile della madre.\n"
            "- Dichiarazione delle pubblicazioni: date e luoghi delle tre pubblicazioni.\n"
            "- Consensi dei genitori se minorenni, o nulla osta se maggiorenni.\n"
            "- Dichiarazione di volontà: formula 'Dichiaro di voler...'; risposta dell'altro sposo.\n"
            "- Proclamazione dell'ufficiale.\n"
            "- Quattro testimoni: nome, cognome, età, professione, domicilio.\n"
            "- Firme degli sposi, dei testimoni, dell'ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il N° atto è in cifre arabiche: trascrivilo con precisione.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCI — Atto di Morte (dal 1866)": (
            "\nTIPOLOGIA: Atto di morte dello Stato Civile Italiano (SCI, dal 1/1/1866).\n"
            "Formato standardizzato prestampato, redatto dall'ufficiale di stato civile comunale.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: N° atto, anno, comune, ufficiale di stato civile.\n"
            "- Formula fissa: 'L'anno... avanti di me... si sono presentati...'\n"
            "- Due dichiaranti: nome, cognome, età, professione, domicilio e relazione col defunto.\n"
            "- Defunto: nome, cognome, luogo e data di nascita (o età), professione, domicilio,"
            " stato civile (celibe/coniugato/vedovo).\n"
            "  Se coniugato o vedovo: nome e cognome del coniuge (con 'fu' se defunto).\n"
            "  Nomi del padre e della madre del defunto (con 'fu' se defunti).\n"
            "- Data, ora e luogo esatto del decesso.\n"
            "- Causa di morte: se indicata, può usare terminologia medica ottocentesca.\n"
            "- Firme dei dichiaranti (o nota di analfabetismo), firma dell'ufficiale.\n"
            "- Dal 1875: possibili annotazioni a margine.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il N° atto è in cifre arabiche: trascrivilo con precisione.\n"
            "- 'Fu' indica genitore o coniuge defunto: trascrivi letteralmente.\n"
            "- Cause di morte arcaiche comuni: 'apoplessia', 'idropisia', 'consunzione',"
            " 'febbre perniciosa', 'mal sottile' (tisi/tubercolosi) — trascrivile esattamente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        "Atto di Stato Civile (Nascita / Battesimo)": (
            "\nTIPOLOGIA: Atto di nascita o battesimo (XIX secolo, registro civile o parrocchiale,"
            " periodo non specificato).\n"
            "- Campi chiave: nome del neonato, genitori (padre e madre con cognome da nubile),"
            " data e luogo di nascita, testimoni, ufficiale o parroco.\n"
            "- I nomi di persona sono spesso abbreviati (Gio. = Giovanni, Batta. = Battista, Fran.co = Francesco).\n"
            "- Il termine 'fu' indica genitore defunto (es. 'figlio di Giovanni fu Isidoro'): trascrivilo letteralmente.\n"
            "- Le date sono in lettere: 'il giorno tre maggio milleottocentosei'.\n"
            "- MARGINALIA: trascrivi qualsiasi annotazione a margine separandola con il tag [MARGINE: ...].\n"
            "- Per cognomi dialettali con variante fonetica plausibile, aggiungi la variante subito dopo"
            " tra parentesi quadre: es. Bortolato [Bortolotti].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con la riga '--- ATTO N ---'"
            " (dove N è il numero progressivo), prima di ogni atto incluso il primo.\n"
        ),
        "Atto di Stato Civile (Matrimonio)": (
            "\nTIPOLOGIA: Atto di matrimonio (XIX secolo, registro civile o parrocchiale).\n"
            "- Campi chiave: sposo e sposa (nome, cognome, età, professione, domicilio),"
            " padri e madri di entrambi (con 'fu' se defunti), testimoni.\n"
            "- Il termine 'fu' indica genitore defunto: trascrivilo letteralmente.\n"
            "- Frequenti formule latine come 'in facie Ecclesiae' nei registri parrocchiali.\n"
            "- MARGINALIA: trascrivi annotazioni a margine (spesso rimandano a successive nascite o morti)"
            " separandole con il tag [MARGINE: ...].\n"
            "- Per cognomi dialettali con variante fonetica plausibile, aggiungi la variante tra parentesi"
            " quadre: es. Mancuso [Mancusa].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con la riga '--- ATTO N ---'"
            " (dove N è il numero progressivo), prima di ogni atto incluso il primo.\n"
        ),
        "Atto di Stato Civile (Morte / Sepoltura)": (
            "\nTIPOLOGIA: Atto di morte o sepoltura (XIX secolo).\n"
            "- Campi chiave: nome e cognome del defunto, età, causa di morte (se indicata),"
            " data e luogo del decesso, dichiaranti, sepoltura.\n"
            "- Il termine 'fu' indica genitore defunto: trascrivilo letteralmente.\n"
            "- Presta attenzione ai termini medici arcaici per le cause di morte.\n"
            "- MARGINALIA: trascrivi annotazioni a margine separandole con il tag [MARGINE: ...].\n"
            "- Per cognomi con variante fonetica plausibile (defunto, dichiaranti o testimoni),"
            " aggiungi la variante tra parentesi quadre: es. Ricci [Rizzi].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con la riga '--- ATTO N ---'"
            " (dove N è il numero progressivo), prima di ogni atto incluso il primo.\n"
        ),
        "Processetto / Allegati Matrimoniali": (
            "\nTIPOLOGIA: Processetto matrimoniale o allegati (documenti istruttori pre-matrimonio).\n"
            "Il processetto include: interrogatori degli sposi e dei testimoni, estratti di battesimo,"
            " estratti di morte dei genitori defunti, eventuali dispense.\n"
            "- Identifica e trascrivi le singole sezioni: intestazione dell'ufficio,"
            " domande del cancelliere, risposte dei comparenti, sottoscrizioni e sigilli.\n"
            "- I comparenti indicano spesso 'figlio/a di ... fu ...' (genitore defunto):"
            " trascrivi 'fu' letteralmente.\n"
            "- Le deposizioni testimoniali iniziano tipicamente con formule come"
            " 'Comparso avanti di me...' o 'Il sottoscritto dichiara...'.\n"
            "- Le dispense papali o vescovili hanno intestazioni in latino: trascrivile integralmente.\n"
            "- Ogni documento all'interno del fascicolo va separato con una riga vuota e il tag"
            " [DOCUMENTO N:] come intestazione.\n"
            "- MARGINALIA: trascrivi annotazioni a margine separandole con il tag [MARGINE: ...].\n"
            "- Se un singolo foglio contiene più deposizioni o atti distinti, separa ciascuno con"
            " '--- ATTO N ---' prima di ogni sezione.\n"
        ),
        "Stati delle Anime Granducato di Toscana": (
            "\nTIPOLOGIA: Stato delle Anime del Granducato di Toscana"
            " (formato codificato dalle Sovrane Disposizioni — Biglietto della R. Segreteria di Stato 12 novembre 1840).\n"
            "\nSTRUTTURA DELLE COLONNE (FISSA PER LEGGE — leggi TUTTE le colonne per ogni riga):\n"
            "  Col.1  = N° Casa\n"
            "  Col.2  = N° Famiglia\n"
            "  Col.3  = N° Progressivo Persona\n"
            "  Col.4  = Cognome\n"
            "  Col.5  = Nome\n"
            "  Col.6  = Età\n"
            "  Col.7  = Stato civile Maschio: Celibe (barrare)\n"
            "  Col.8  = Stato civile Maschio: Ammogliato (barrare)\n"
            "  Col.9  = Stato civile Maschio: Vedovo (barrare)\n"
            "  Col.10 = Stato civile Femmina: Nubile (barrare)\n"
            "  Col.11 = Stato civile Femmina: Maritata (barrare)\n"
            "  Col.12 = Stato civile Femmina: Vedova (barrare)\n"
            "  Col.14 = Religione\n"
            "  Col.15 = Patria (luogo di origine)\n"
            "  Col.16 = Professione\n"
            "  Col.19 = Osservazioni\n"
            "\nREGOLE OBBLIGATORIE PER LA TRASCRIZIONE A TABELLA:\n"
            "- Trascrivi OGNI riga come una riga di testo con i valori separati da ' | ',"
            " nell'ordine: N°Casa | N°Fam | Prog | Cognome | Nome | Età | Celibe | Ammogliato | Vedovo"
            " | Nubile | Maritata | Vedova | Religione | Patria | Professione | Osservazioni\n"
            "- Inizia con una riga di intestazione con i nomi delle colonne separati da ' | '.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore precedente in quella colonna:\n"
            "  TRASCRIVILI come \" senza espanderli.\n"
            "- Le colonne stato civile (7–12) contengono un segno grafico (croce, tratto, X) o sono vuote:\n"
            "  trascrivi '1' se barrata, '' se vuota.\n"
            "- REGOLA GENERE — LE COLONNE COMANDANO SUL NOME: il segno nelle caselle stato civile è"
            " un dato fisico certo. PROCEDURA: (1) conta le 6 caselle nell'ordine"
            " Celibe | Ammogliato | Vedovo | Nubile | Maritata | Vedova;"
            " (2) se il segno è nella posizione 1, 2 o 3 → persona MASCHIO;"
            " se nella posizione 4, 5 o 6 → persona FEMMINA;"
            " (3) solo DOPO aver stabilito il genere dalle caselle, verifica il nome:"
            " se il nome letto non corrisponde al genere (es. nome in -a per un maschio),"
            " correggi il nome al genere indicato dalle caselle"
            " (es. 'Angelina' → 'Angelino', 'Giuseppa' → 'Giuseppe', 'Giovanna' → 'Giovanni')."
            " Le caselle prevalgono SEMPRE sul nome, mai il contrario.\n"
            "- NON saltare righe: anche le righe con soli segni ditto vanno trascritte.\n"
            "- Se una colonna è vuota scrivi uno spazio tra i separatori: | |\n"
            "- Se un valore è illeggibile usa [?].\n"
            "- TRASCRIVI NOMI E COGNOMI ESATTAMENTE come scritti: non correggere, non normalizzare.\n"
            "- N°CASA E N°FAMIGLIA NELLE RIGHE DI CONTINUAZIONE: per le persone che non sono"
            " capofamiglia, le colonne N°Casa (col.1) e N°Famiglia (col.2) sono BLANK (vuote);"
            " il numero progressivo crescente si trova SEMPRE nella terza colonna (N°Progressivo)."
            " NON scrivere il progressivo in col.2.\n"
            "  ESEMPIO riga capofamiglia:  1 | 1 | 1 | Acciaj | Gaspero | 60 |  | 1 |  |  |  |  | ...\n"
            "  ESEMPIO riga continuazione: |  | 2 | \" | Rosa | 62 |  |  |  |  | 1 |  | ...\n"
            "- RIGHE PER PAGINA: il modello imposto dal Biglietto 1840 prevede ESATTAMENTE 25 righe"
            " dati per pagina (da progressivo 1 a 25, o continuazione del progressivo del fascicolo)."
            " Nelle pagine intermedie ci sono sempre 25 righe; solo l'ultima pagina del registro può"
            " averne meno. Se vedi righe vuote fino a 25, trascrivile come righe vuote (tutti | |)."
            " Non inventare righe oltre quelle realmente presenti nell'immagine.\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
            "- ETÀ A DUE CIFRE: l'età è un numero intero scritto in cifre arabiche (1-3 cifre)."
            " Leggi TUTTE le cifre: non trascrivere '4' se nel registro è scritto '40',"
            " né '2' se è '22', né '1' se è '18', né '4' se è '44'."
            " Le decine e le unità sono scritte ravvicinate in corsivo: scorri tutta la casella."
            " CIFRE COMUNI IN CORSIVO TOSCANO 1840: '3' e '9' si distinguono per il gambo inferiore"
            " (il '3' è aperto, il '9' ha una coda chiusa); '1' e '2' sono cifre singole brevi;"
            " '11', '22', '33', '44' hanno entrambe le cifre — non leggerne solo una."
            " In caso di dubbio usa [?] dopo l'età ma trascrivi comunque entrambe le cifre viste.\n"
            "- MOGLIE DEL CAPOFAMIGLIA: la prima persona femmina registrata dopo un capofamiglia"
            " con col.8 (Ammogliato) barrata è SEMPRE sua moglie → Maritata (col.11 barrata)."
            " Le figlie nubili vengono elencate DOPO la moglie. Non confondere moglie con figlia."
            " Se una donna adulta (età > 15) segue immediatamente un Ammogliato nello stesso nucleo,"
            " verificare sempre che la casella col.11 sia barrata nell'immagine.\n"
            "- COGNOMI E NOMI — FEDELTÀ ASSOLUTA: trascrivi ogni cognome e nome ESATTAMENTE"
            " come scritto nel documento, lettera per lettera. Non correggere, non normalizzare:"
            " 'Luisa' rimane 'Luisa' (non 'Luigia'),"
            " 'Angelo' rimane 'Angelo' (non 'Angiolo'), 'Santi' rimane 'Santi' (non 'Sante'),"
            " 'Angelino' rimane 'Angelino' (non 'Angiolino'), 'Andrei' rimane 'Andrei' (non 'Andreini').\n"
            "- ABBREVIAZIONI NEI NOMI: NON usare mai le parentesi angolate < > per i nomi propri"
            " di persona. I nomi di persona vanno trascritti SEMPRE per intero."
            " Le parentesi angolate < > sono riservate alle abbreviazioni di termini comuni (es. titoli,"
            " professioni, formule), MAI per nomi o cognomi. Scrivi 'Bernardo' non 'Bernard<o>',"
            " 'Giovanni' non 'Giov<anni>', 'Caterina' non 'Cat<erina>'.\n"
            "- GENDER RULE — BAMBINI PICCOLI: per bambini di età 0-3 anni la grafia corsiva del nome"
            " può essere ambigua. PROCEDURA: (1) conta la casella barrata per il genere"
            " (caselle 1-3=maschio/Celibe, caselle 4-6=femmina/Nubile); (2) trascrivi il nome"
            " ESATTAMENTE come scritto nel documento, qualunque esso sia."
            " NON correggere un nome femminile in maschile o viceversa basandoti sulle caselle:"
            " un bambino di 1 anno può chiamarsi 'Tina' (femmina, Nubile) o 'Pietro' (maschio, Celibe)."
            " Le caselle determinano la colonna stato civile, NON il nome."
            " Se il nome è illeggibile scrivi [?].\n"
            "- COLONNE STATO CIVILE FEMMINILE: col.10=Nubile, col.11=Maritata, col.12=Vedova."
            " Conta rigorosamente le 6 caselle stato civile da sinistra: Celibe(7)|Ammogliato(8)|Vedovo(9)|Nubile(10)|Maritata(11)|Vedova(12)."
            " Non confondere col.10 con col.11: una croce nella quarta casella = Nubile, nella quinta = Maritata.\n"
            "- CAPOFAMIGLIA AMMOGLIATO: quando una riga capofamiglia ha col.8=1 (Ammogliato),"
            " significa che è sposato. La sua colonna stato civile è la SECONDA delle sei caselle."
            " Non confondere con Celibe (prima casella). Es.: `4 | 4 | 13 | Bargelli | Pietro | 42 |  | 1 |  |  |  |  | ...`"
            " — il '1' è nella seconda posizione = Ammogliato, non Celibe.\n"
            "- REGOLA ETÀ-STATO CIVILE (vincolo assoluto): un individuo con età ≤ 14 anni NON PUÒ"
            " essere Ammogliato (col.8), Maritata (col.11), Vedovo (col.9) o Vedova (col.12)."
            " Per ogni persona con età ≤ 14, la colonna barrata è OBBLIGATORIAMENTE"
            " Celibe (col.7, maschio) o Nubile (col.10, femmina)."
            " Se la lettura ti suggerisce un'altra colonna per un under-15, hai contato male le caselle:"
            " riconsidera la posizione del segno con questa certezza come vincolo.\n"
            "- VERIFICA COERENZA NUCLEO FAMILIARE: dopo aver trascritto tutte le righe di un nucleo,"
            " controlla: (a) se il capofamiglia ha Ammogliato=1, nel nucleo DEVE comparire esattamente"
            " una donna con Maritata=1 (la moglie). Se non trovi nessuna Maritata, hai attribuito"
            " Nubile (col.10) invece di Maritata (col.11) alla moglie — rileggi la sua riga."
            " (b) se il capofamiglia ha Celibe=1 o Vedovo=1, non ci sono Maritate nel nucleo"
            " (a meno di figli già sposati conviventi, raro in questa tipologia).\n"
            "- COGNOMI DIFFICILI: alcuni cognomi in corsivo toscano hanno lettere molto simili:"
            " 'Bargelli' (con doppia 'l' e finale 'i') non è 'Bargilli';"
            " 'Bertoni' (con 'o') non è 'Bertini' (con 'i')."
            " In caso di dubbio tra 'e'/'i' o 'o'/'i' in un cognome, trascrivi esattamente"
            " le lettere che vedi senza modificare, e aggiungi [?] solo se veramente illeggibile.\n"
            "- NEONATI (età 0-1): un bambino di 1 anno può essere maschio (Celibe, col.7) O femmina"
            " (Nubile, col.10). Leggi PRIMA la casella per determinare il genere,"
            " poi trascrivi il NOME ESATTAMENTE come scritto: 'Tina' è un nome femminile valido"
            " (Nubile), 'Pietro' è maschile (Celibe). NON sovrascrivere mai il nome letto.\n"
        ),
        "Stato delle Anime / Censimento Parrocchiale": (
            "\nTIPOLOGIA: Stato delle Anime o censimento parrocchiale (TABELLA MULTI-COLONNA).\n"
            "\nSTRUTTURA ATTESA DELLE COLONNE (leggi TUTTE le colonne per ogni riga):\n"
            "  Col.1 = N° d'ordine Casa | Col.2 = N° Famiglia | Col.3 = N° Persona\n"
            "  Col.4 = Cognome | Col.5 = Nome | Col.6 = Età | Col.7 = Stato civile\n"
            "  Col.8 = Religione/Patria | Col.9 = Professione | Col.10 = Osservazioni\n"
            "\nREGOLE OBBLIGATORIE PER LA TRASCRIZIONE A TABELLA:\n"
            "- Trascrivi OGNI riga come una riga di testo con i valori separati da ' | '.\n"
            "  Esempio: 1 | 1 | 1 | Davini | Enrico | 45 | M | Poncarale | Contadino |\n"
            "- Inizia con una riga di intestazione con i nomi delle colonne separati da ' | '.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore precedente in quella colonna:\n"
            "  TRASCRIVILI come \" senza espanderli.\n"
            "- NON saltare righe: anche le righe con soli segni ditto vanno trascritte.\n"
            "- Se una colonna è vuota scrivi uno spazio tra i separatori: | |\n"
            "- Se un valore è illeggibile usa [?].\n"
            "- NON aggiungere note o commenti: solo la tabella.\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
        ),
        "Censimento Storico (Generico)": (
            "\nTIPOLOGIA: Censimento storico (es. censimento statale 1861, 1871, 1881, 1901).\n"
            "- La struttura è tabellare: trascrivi ogni riga con i valori separati da ' | '.\n"
            "- Inizia con una riga di intestazione riportando i nomi delle colonne come indicati nel documento.\n"
            "- Colonne tipiche: N° ordine | Cognome e Nome | Relazione col capofamiglia"
            " | Sesso | Anno di nascita | Stato civile | Professione | Istruzione | Note.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore soprastante:"
            " TRASCRIVILI come \" senza espanderli.\n"
            "- NON saltare righe vuote o con soli segni ditto.\n"
            "- Se un valore è illeggibile usa [?].\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
        ),
        "Documento Notarile": (
            "\nTIPOLOGIA: Documento notarile (contratto, testamento, atto di compravendita, ecc.).\n"
            "- Formula di apertura tipica: 'In Dei nomine amen...' o 'Regnante...'\n"
            "- Presta attenzione ai nomi delle parti contraenti, testimoni, notaio rogante.\n"
            "- Le abbreviazioni dei titoli (Ser, Dominus, fu = quondam) sono frequenti.\n"
            "- Conserva le formule legali anche se apparentemente ridondanti.\n"
            "- Il termine 'fu' equivale al latino 'quondam': trascrivilo letteralmente.\n"
            "- Per cognomi con variante grafica (es. forme latinizzate o dialettali),"
            " aggiungi la variante tra parentesi quadre: es. De Marchi [de Marchis].\n"
        ),
        "Atto in Latino Ecclesiastico": (
            "\nTIPOLOGIA: Atto ecclesiastico in latino (registro parrocchiale pre-napoleonico,"
            " dispensa, atto sinodale, necrologio, ecc.).\n"
            "- Trascrivi il testo in latino esattamente come scritto, senza tradurre.\n"
            "- Le abbreviazioni latine sono frequentissime: sciogli quelle ovvie"
            " tra parentesi angolate < >. Es: Xbris = <Decembris>, 7bris = <Septembris>,"
            " Joannis = <Johannis>, fil. = <filius/filia>, ux. = <uxor>.\n"
            "- Il 'fu' si esprime in latino come 'quondam' (qm, q.m): trascrivilo letteralmente.\n"
            "- Le date usano lo stile romano (Kalendas, Nonas, Idus) o l'anno ab Incarnatione:"
            " trascrivile come appaiono.\n"
            "- Mantieni la struttura del documento: formula di apertura, corpo, sottoscrizioni,"
            " sigilli o croci notarili.\n"
            "- MARGINALIA: trascrivi annotazioni a margine separandole con il tag [MARGINE: ...].\n"
        ),
        "Lettera / Corrispondenza Privata": (
            "\nTIPOLOGIA: Lettera o corrispondenza privata.\n"
            "- Mantieni l'intestazione (luogo, data) e la formula di chiusura.\n"
            "- La grafia privata è spesso corsiva e irregolare: privilegia la lettura letterale.\n"
            "- Non correggere errori ortografici o grammaticali dello scrivente.\n"
        ),
        "Testo a Stampa Antico": (
            "\nTIPOLOGIA: Testo a stampa antico (incunabolo, cinquecentina, ecc.).\n"
            "- Distingui la 's' lunga (ſ) dalla 'f' moderna.\n"
            "- Mantieni le varianti grafiche arcaiche (ex → et, & → e, œ, æ).\n"
            "- Segnala le interruzioni di pagina con [PAGINA NUOVA].\n"
        ),
        "Indice / Registro degli Atti": (
            "\nTIPOLOGIA: Indice o sommario di registro storico (indice degli atti di nascita, matrimonio,"
            " morte, o altro registro civile/parrocchiale).\n"
            "- La struttura è tabellare o a elenco: trascrivi fedelmente ogni riga.\n"
            "- Colonne tipiche: N° atto | Cognome e Nome | Data | Pagina/Foglio | Note.\n"
            "- Usa ' | ' come separatore di colonna; includi una riga di intestazione con i nomi"
            " delle colonne come indicati nel registro.\n"
            "- Trascrivi i cognomi esattamente come scritti, senza normalizzare.\n"
            "- I numeri di atto o di pagina/foglio sono riferimenti critici: trascrivili con"
            " massima precisione.\n"
            "- Se l'indice è su più colonne affiancate (es. due colonne per A–M e N–Z),"
            " trascrivile come due blocchi separati da una riga vuota, ognuno con la propria intestazione.\n"
            '- I segni ditto (") o \'idem\' indicano cognome uguale alla riga precedente:'
            ' TRASCRIVILI come " senza espanderli.\n'
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
        ),
        "Documento Generico / Non Classificato": (
            "\nTIPOLOGIA: Documento non classificato (nessuna tipologia predefinita applicabile).\n"
            "- Trascrivi il testo esattamente come appare, preservando la struttura visiva originale.\n"
            "- Se il documento ha colonne o tabelle, usa ' | ' come separatore di colonna.\n"
            "- Se il documento ha sezioni distinte (titoli, paragrafi, firme), separale con una riga vuota.\n"
            "- Segnala con [MARGINE: ...] qualsiasi annotazione a margine o fuori dal corpo principale.\n"
        ),
    }

    specific = type_specific.get(doc_type, type_specific["Documento Generico / Non Classificato"])

    prompt = base + specific

    if example_text.strip():
        prompt += (
            "\n\n--- TRASCRIZIONE DI RIFERIMENTO ---\n"
            "La seguente trascrizione è di una pagina dello stesso documento.\n"
            "Usala per imparare la calligrafia e il vocabolario specifico dello scrivano:\n\n"
            f"{example_text.strip()}\n"
            "--- FINE RIFERIMENTO ---\n"
        )

    if user_instructions.strip():
        prompt += f"\n\n--- ISTRUZIONI AGGIUNTIVE ---\n{user_instructions.strip()}\n"

    prompt += "\n\nINIZIA ORA LA TRASCRIZIONE:"
    return prompt
