"""
Prompt di base per l'OCR Avanzato, divisi per tipologia documentale.
Ogni tipo fornisce linee guida paleografiche specifiche all'IA.
"""


def get_available_types():
    return [
        # ── Stato Civile Napoleonico (SCN, 1806-1815) ──────────────────────────
        "SCN — Atto di Nascita (1806-1815)",
        "SCN — Atto di Matrimonio (1806-1815)",
        "SCN — Atto di Morte (1806-1815)",
        # ── Stato Civile della Restaurazione (SCR, 1815-1865) ─────────────────
        "SCR — Atto di Nascita (1815-1865)",
        "SCR — Atto di Matrimonio (1815-1865)",
        "SCR — Atto di Morte (1815-1865)",
        # ── SCR — varianti regionali ───────────────────────────────────────────
        "SCR/Toscana — Atto di Nascita (1817-1865)",
        "SCR/Toscana — Atto di Matrimonio (1817-1865)",
        "SCR/Toscana — Atto di Morte (1817-1865)",
        "SCR/Due Sicilie — Atto di Nascita (1816-1865)",
        "SCR/Due Sicilie — Atto di Matrimonio (1816-1865)",
        "SCR/Due Sicilie — Atto di Morte (1816-1865)",
        "SCR/Piemonte — Atto di Nascita (1837-1865)",
        "SCR/Piemonte — Atto di Matrimonio (1837-1865)",
        "SCR/Piemonte — Atto di Morte (1837-1865)",
        # ── SCR/Veneto (Lombardo-Veneto / Impero austriaco, 1816-1866) ─────────
        "SCR/Veneto — Atto di Nascita (1816-1866)",
        "SCR/Veneto — Atto di Matrimonio (1816-1866)",
        "SCR/Veneto — Atto di Morte (1816-1866)",
        # ── Stato Civile Italiano (SCI, dal 1866) ─────────────────────────────
        "SCI — Atto di Nascita (dal 1866)",
        "SCI — Atto di Matrimonio (dal 1866)",
        "SCI — Atto di Morte (dal 1866)",
        # ── Periodo incerto / generico ─────────────────────────────────────────
        "Atto di Stato Civile (Nascita / Battesimo)",
        "Atto di Stato Civile (Matrimonio)",
        "Atto di Stato Civile (Morte / Sepoltura)",
        "Processetto / Allegati Matrimoniali",
        "Pubblicazioni di Matrimonio (registro bandi)",
        # ── Registri Parrocchiali (Concilio di Trento, sec. XVI-XIX) ───────────────
        "Registro Parrocchiale — Battesimi (sec. XVI-XIX)",
        "Registro Parrocchiale — Matrimoni (sec. XVI-XIX)",
        "Registro Parrocchiale — Morti / Sepolture (sec. XVI-XIX)",
        "Registro degli Esposti / Nati Illegittimi",
        "Stati delle Anime Granducato di Toscana",
        "Anagrafe / Censimento Lombardo-Veneto (sec. XIX)",
        "Stato delle Anime / Censimento Parrocchiale",
        "Censimento Storico (Generico)",
        "Catasto Onciario (Due Sicilie, sec. XVIII)",
        "Catasto Gregoriano (Stato Pontificio, 1816-1835)",
        # ── Leva Militare (1865-1940) ──────────────────────────────────────────────────
        "Ruolo di Matricola / Leva Militare (1865-1940)",
        "Foglio Matricolare (scheda individuale, 1865-1940)",
        # ── Emigrazione e documenti di viaggio (sec. XIX-XX) ──────────────────
        "Passaporto / Permesso di Espatrio (sec. XIX-XX)",
        "Atti Consolari Italiani all'Estero",
        "Indice / Registro degli Atti",
        "Documento Notarile",
        "Atto in Latino Ecclesiastico",
        "Lettera / Corrispondenza Privata",
        "Testo a Stampa Antico",
        "Documento Generico / Non Classificato",
    ]


def compose_ocr_prompt(doc_type, user_instructions="", example_text=""):
    """
    Costruisce il prompt per la trascrizione paleografica in base alla tipologia.
    """
    base = (
        "Sei un esperto paleografo con specializzazione in documenti storici italiani.\n"
        "COMPITO: Trascrivi FEDELMENTE il testo contenuto nell'immagine.\n\n"
        "REGOLE ASSOLUTE:\n"
        "1. Non normalizzare nomi propri, cognomi o termini dialettali: trascrivili esattamente come scritti.\n"
        "2. Mantieni la disposizione del testo originale (a capo, paragrafi, colonne).\n"
        "3. Indica le letture incerte con [?] immediatamente dopo la parola dubia.\n"
        "4. Sciogli le abbreviazioni ovvie tra parentesi angolate < >.\n"
        "5. Non aggiungere commenti, titoli o note a margine: solo il testo trascritto.\n"
    )

    type_specific = {
        # ── SCN: Stato Civile Napoleonico (1806-1815) ──────────────────────────
        "SCN — Atto di Nascita (1806-1815)": (
            "\nTIPOLOGIA: Atto di nascita dello Stato Civile Napoleonico (SCN, 1806-1815).\n"
            "Il SCN fu introdotto con il Codice Civile francese e redatto dagli ufficiali comunali"
            " (sindaco o delegato), NON dai parroci.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno in lettere ('L'anno milleottocentosei'), giorno e mese in lettere,"
            " nome del comune, nome e qualifica dell'ufficiale di stato civile.\n"
            "- Comparente: il padre (o, in sua assenza, due testimoni adulti maschi) che 'presenta'"
            " il neonato fisicamente all'ufficiale. Dati: nome, cognome, età, professione, domicilio.\n"
            "- Neonato: sesso ('di sesso maschile/femminile'), nome imposto, data e ora di nascita.\n"
            "- Due testimoni maschi maggiorenni: nome, cognome, età, professione, domicilio.\n"
            "- Formula di chiusura: lettura dell'atto, firme del dichiarante e dei testimoni"
            " (o croce/nota 'ha dichiarato di non saper firmare'), firma dell'ufficiale.\n"
            "- N° atto: in genere nel margine sinistro o nell'intestazione.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date sono in lettere: 'il giorno tre maggio milleottocentosei'.\n"
            "- Il termine 'fu' indica genitore defunto: trascrivilo letteralmente.\n"
            "- Abbreviazioni frequenti: Gio. = Giovanni, Batta. = Battista, Fran.co = Francesco.\n"
            "- MARGINALIA: trascrivi annotazioni a margine con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCN — Atto di Matrimonio (1806-1815)": (
            "\nTIPOLOGIA: Atto di matrimonio dello Stato Civile Napoleonico (SCN, 1806-1815).\n"
            "Redatto dall'ufficiale di stato civile comunale, preceduto da tre pubblicazioni (bandi).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, giorno, mese in lettere; comune; nome dell'ufficiale.\n"
            "- Sposo: nome, cognome, età, professione, domicilio, stato civile (celibe/vedovo);"
            " nome del padre (con 'fu' se defunto) e della madre.\n"
            "- Sposa: stesse informazioni dello sposo; cognome da nubile della madre.\n"
            "- Consensi parentali: se uno degli sposi è minorenne, sono riportati i consensi"
            " dei genitori (o, se defunti, del consiglio di famiglia).\n"
            "- Dichiarazione di volontà: formula 'Dichiaro di voler prendere per mio/a sposo/a'"
            " o equivalente; risposta dell'altro sposo.\n"
            "- Proclamazione dell'ufficiale: formula 'In nome della legge dichiaro uniti in matrimonio'.\n"
            "- Quattro testimoni maschi maggiorenni: nome, cognome, età, professione, domicilio.\n"
            "- Firme degli sposi, dei testimoni, dell'ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date sono in lettere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Le pubblicazioni precedono l'atto e vanno trascritte separatamente con [PUBBLICAZIONE N:].\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCN — Atto di Morte (1806-1815)": (
            "\nTIPOLOGIA: Atto di morte dello Stato Civile Napoleonico (SCN, 1806-1815).\n"
            "Redatto dall'ufficiale di stato civile comunale su dichiarazione di due testimoni.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, giorno, mese in lettere; comune; nome dell'ufficiale.\n"
            "- Due dichiaranti (spesso vicini di casa, parenti o colleghi del defunto):"
            " nome, cognome, età, professione, domicilio e loro qualifica di conoscenza.\n"
            "- Defunto: nome, cognome, età (o data di nascita), professione, domicilio,"
            " stato civile (celibe/coniugato/vedovo), nome del coniuge se coniugato,"
            " nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora e luogo del decesso.\n"
            "- Firme dei dichiaranti (o nota di analfabetismo), firma dell'ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date sono in lettere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Presta attenzione ai termini arcaici per le cause di morte (se indicate).\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR: Stato Civile della Restaurazione (1815-1865) ─────────────────
        "SCR — Atto di Nascita (1815-1865)": (
            "\nTIPOLOGIA: Atto di nascita dello Stato Civile della Restaurazione (SCR, 1815-1865).\n"
            "Dopo il 1815, ogni Stato pre-unitario adottò un sistema proprio. Il formato varia"
            " significativamente per area geografica:\n"
            "- Granducato di Toscana (dal 1817): compilato dal parroco con duplice copia all'Ufficio"
            " dello Stato Civile di Firenze; struttura simile al SCN ma con formule miste civili"
            " ed ecclesiastiche.\n"
            "- Regno delle Due Sicilie (dal 1816) e Sicilia (dal 1820): formula simile al SCN.\n"
            "- Ducato di Modena e Reggio: mantenne il sistema napoleonico quasi invariato.\n"
            "- Regno di Sardegna (dal 1837): formato ibrido piemontese.\n"
            "\nELEMENTI COMUNI A TUTTE LE VARIANTI:\n"
            "- Intestazione con anno, data, comune, ufficiale o parroco.\n"
            "- Comparente (padre o suoi delegati) che presenta il neonato.\n"
            "- Sesso, nome e data di nascita del neonato.\n"
            "- Nomi dei genitori e almeno un avo (con 'fu' se defunti).\n"
            "- Due o più testimoni con dati anagrafici.\n"
            "- Firme o note di analfabetismo, firma del redattore.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date possono essere in lettere o in cifre a seconda del sistema locale.\n"
            "- 'Fu' (o 'quondam'/'q.m' nei testi latini) indica genitore defunto.\n"
            "- In Toscana frequenti formule religiose anche negli atti civili.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR — Atto di Matrimonio (1815-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio dello Stato Civile della Restaurazione (SCR, 1815-1865).\n"
            "Il formato varia per area geografica (vedi SCR-Nascita per le varianti regionali).\n"
            "\nELEMENTI COMUNI:\n"
            "- Intestazione con anno, data, comune, ufficiale o parroco officiante.\n"
            "- Sposo e sposa con dati anagrafici completi (nome, cognome, età, professione,"
            " domicilio, stato civile, nome dei genitori con 'fu' se defunti).\n"
            "- Consensi parentali o del consiglio di famiglia per i minorenni.\n"
            "- Pubblicazioni (bandi) precedenti: spesso richiamati nell'atto con date e luoghi.\n"
            "- Dichiarazione di volontà di entrambi gli sposi.\n"
            "- Testimoni (due o quattro a seconda del sistema) con dati anagrafici.\n"
            "- In Toscana: possibile presenza di formule religiose e riferimenti al diritto canonico"
            " nell'atto civile.\n"
            "- Firme degli sposi, dei testimoni, dell'ufficiale o parroco.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Le date possono essere in lettere o in cifre.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR — Atto di Morte (1815-1865)": (
            "\nTIPOLOGIA: Atto di morte dello Stato Civile della Restaurazione (SCR, 1815-1865).\n"
            "Il formato varia per area geografica (vedi SCR-Nascita per le varianti regionali).\n"
            "\nELEMENTI COMUNI:\n"
            "- Intestazione con anno, data, comune, ufficiale o parroco.\n"
            "- Due dichiaranti con dati anagrafici e relazione col defunto.\n"
            "- Defunto: nome, cognome, età, professione, domicilio, stato civile,"
            " nome del coniuge se coniugato o vedovo, nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora (a volte) e luogo del decesso.\n"
            "- Causa di morte: quando indicata, usa terminologia arcaica o dialettale.\n"
            "- Firme o note di analfabetismo, firma del redattore.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- In Toscana frequenti formule religiose (es. 'munito dei SS. Sacramenti').\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR/Toscana (Granducato, 1817-1865) ───────────────────────────────
        "SCR/Toscana — Atto di Nascita (1817-1865)": (
            "\nTIPOLOGIA: Atto di nascita del Granducato di Toscana (SCR/Toscana, 1817-1865).\n"
            "Regolato dalla legge toscana sullo stato civile del 1817. L'ufficiale è il PARROCO\n"
            "della parrocchia, nominato delegato dello Stato. L'atto ha doppia natura\n"
            "civile-ecclesiastica ed è compilato in DOPPIO ORIGINALE: uno conservato in parrocchia,\n"
            "uno inviato all'Ufficio di Stato Civile di Firenze.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno in cifre arabiche, giorno e mese, nome della parrocchia,"
            " nome e titolo del sacerdote-ufficiale ('io sottoscritto Sacerdote N.N. Parroco di...').\n"
            "- Comparente: di norma il padre, comparso 'avanti di me'; nome, cognome, età,"
            " professione, domicilio.\n"
            "- Neonato: sesso, nome imposto, data e ora di nascita.\n"
            "- Battesimo: spesso indicato nell'atto stesso ('da me battezzato il giorno...' o"
            " 'battezzato nella stessa giornata'): trascrivilo per intero.\n"
            "- Padre e madre: nome, cognome da nubile della madre, stato civile, professione,"
            " domicilio.\n"
            "- Due testimoni: nome, cognome, età, professione, parrocchiani noti al sacerdote.\n"
            "- Formula di chiusura con elementi ecclesiastici intercalati.\n"
            "- Firma del sacerdote-parroco con titolo; N° atto in margine o intestazione.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- L'anno è in cifre arabiche (differenza rispetto al SCN).\n"
            "- Formule religiose intercalate nel testo civile: trascrivile per intero.\n"
            "- Il riferimento al battesimo è strutturale: se presente, trascrivilo.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Script: corsivo toscano ottocentesco; cancelleresca residua nei registri ante 1830.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Toscana — Atto di Matrimonio (1817-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio del Granducato di Toscana (SCR/Toscana, 1817-1865).\n"
            "Il parroco svolge il triplice ruolo di ministro del sacramento, ufficiale dello stato"
            " civile e testimone istituzionale. L'atto civile e il verbale canonico quasi coincidono.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, parrocchia, nome del sacerdote-ufficiale.\n"
            "- Tre pubblicazioni (bandi): elencate con date domenicali; talvolta riportate\n"
            "  nell'atto stesso, talvolta come documento separato allegato.\n"
            "- Sposo: nome, cognome, età, professione, domicilio, stato civile (celibe/vedovo),"
            " padre e madre (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile.\n"
            "- Consensi parentali se minorenni (uomini sotto 25 anni, donne sotto 21).\n"
            "- Dichiarazione di volontà di entrambi gli sposi.\n"
            "- Almeno due testimoni, spesso quattro; dati anagrafici completi.\n"
            "- Formula di chiusura mista canonica e civile: trascrivila per intero.\n"
            "- Firme degli sposi (o croci), testimoni, sacerdote-ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Formule latine canoniche possono essere intercalate nel testo italiano.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Toscana — Atto di Morte (1817-1865)": (
            "\nTIPOLOGIA: Atto di morte del Granducato di Toscana (SCR/Toscana, 1817-1865).\n"
            "Compilato dal parroco come ufficiale delegato. Spesso include anche la registrazione\n"
            "della sepoltura (luogo e data).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, parrocchia, sacerdote-ufficiale.\n"
            "- Due dichiaranti (di norma vicini o parenti): nome, cognome, età, professione,"
            " relazione col defunto.\n"
            "- Defunto: nome, cognome, età, professione, domicilio, stato civile,"
            " nome del coniuge superstite (o 'vedovo/vedova di'), nomi dei genitori (con 'fu').\n"
            "- Data, ora e luogo del decesso.\n"
            "- Causa di morte: spesso con terminologia arcaica o religiosa ('vizio di petto',"
            " 'accidente apoplettico', 'munito dei SS. Sacramenti').\n"
            "- Note di sepoltura: luogo (chiesa, camposanto), data, sacramenti ricevuti.\n"
            "- Firme o croci dei dichiaranti, firma del sacerdote-ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Munito dei SS. Sacramenti' o formule simili: trascrivi per intero.\n"
            "- Cause di morte in terminologia arcaica: non correggere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR/Due Sicilie (Regno delle Due Sicilie, 1816-1865) ───────────────
        "SCR/Due Sicilie — Atto di Nascita (1816-1865)": (
            "\nTIPOLOGIA: Atto di nascita del Regno delle Due Sicilie (SCR/Due Sicilie,"
            " 1816-1865; Sicilia dal 1820).\n"
            "Istituito da Ferdinando I. L'ufficiale è il SINDACO DECURIONALE (o delegato),"
            " figura tipica dell'amministrazione borbonica.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, 'avanti di me Sindaco del Comune di... /"
            " Ufficiale dello Stato Civile', nome del sindaco o delegato.\n"
            "- Comparente: il padre; formula tipica: 'è comparso N.N. di anni X, di professione"
            " Y, domiciliato in...'.\n"
            "- Neonato: sesso, nome, data e ora di nascita, luogo.\n"
            "- 'Figlio legittimo di' [padre] e di [madre con cognome da nubile].\n"
            "- Madre: nome, cognome da nubile, età, professione, domicilio.\n"
            "- Due testimoni maschi con dati anagrafici completi.\n"
            "- Formula di chiusura e firme.\n"
            "\nPARTICOLARITÀ DEL SISTEMA BORBONICO:\n"
            "- L'ufficio è detto 'Decurionato' (non 'Municipio'): trascrivilo esattamente.\n"
            "- L'ufficiale può essere 'il Sindaco', 'il Vice-Sindaco' o 'l'Eletto al quartiere'.\n"
            "- Formula 'di anni X' per l'età (non solo la cifra come nel SCN).\n"
            "- Sicilia: cognomi e nomi spesso in forma dialettale siciliana (es. 'Ncolò',"
            " 'Agustinu', 'Salvaturi'): non correggere, trascrivili esattamente.\n"
            "- Dialettalismi in cognomi calabresi, pugliesi, campani: trascrivi esattamente.\n"
            "- Script: corsivo meridionale; tratti barocchi nei registri anteriori al 1840.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Due Sicilie — Atto di Matrimonio (1816-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio del Regno delle Due Sicilie (SCR/Due Sicilie, 1816-1865).\n"
            "L'atto civile è separato dal canonico ma celebrato di norma lo stesso giorno."
            " Il Sindaco Decurionale presiede la cerimonia civile.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Sindaco Decurionale o delegato.\n"
            "- Tre pubblicazioni: citate con date e luoghi; formula 'fatte le tre debite pubblicazioni'.\n"
            "- Sposo: nome, cognome, età ('di anni X'), professione, domicilio, stato civile,"
            " padre e madre (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile.\n"
            "- Dichiarazione di volontà: formula 'dichiara di voler prendere in moglie / marito'.\n"
            "- QUATTRO testimoni (a differenza del SCN che ne richiedeva due): dati anagrafici.\n"
            "- Formula di proclamazione del sindaco.\n"
            "- Firme o croci degli sposi, dei quattro testimoni, del sindaco.\n"
            "\nPARTICOLARITÀ:\n"
            "- 'Decurionato' come termine istituzionale: trascrivilo esattamente.\n"
            "- Quattro testimoni: caratteristica borbonica, diversa dal SCN (due testimoni).\n"
            "- Dialettalismi nei nomi e cognomi: non correggere.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Due Sicilie — Atto di Morte (1816-1865)": (
            "\nTIPOLOGIA: Atto di morte del Regno delle Due Sicilie (SCR/Due Sicilie, 1816-1865).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Sindaco Decurionale o delegato.\n"
            "- Due dichiaranti: nome, cognome, età, professione, relazione col defunto.\n"
            "- Defunto: nome, cognome, età ('di anni X'), professione, domicilio, stato civile,"
            " nome del coniuge se coniugato/vedovo, nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora e luogo del decesso.\n"
            "- Causa di morte: frequentemente in terminologia arcaica e/o dialettale meridionale\n"
            "  ('febbre nervina', 'mal di petto', 'mal di cuore', 'colpo apoplettico', 'tisì').\n"
            "- Note religiose: 'munito dei sacramenti', 'senza sacramenti per morte improvvisa'.\n"
            "- Firme o croci dei dichiaranti, firma del sindaco.\n"
            "\nPARTICOLARITÀ:\n"
            "- 'Decurionato' come termine istituzionale: trascrivilo esattamente.\n"
            "- Cause di morte in dialetto meridionale o siciliano: non correggere, trascrivi letteralmente.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR/Piemonte (Regno di Sardegna — Codice Albertino, 1837-1865) ────
        "SCR/Piemonte — Atto di Nascita (1837-1865)": (
            "\nTIPOLOGIA: Atto di nascita del Regno di Sardegna — Codice Albertino"
            " (SCR/Piemonte, 1837-1865).\n"
            "Istituito con le Regie Patenti del 20 aprile 1837. Applicato in Piemonte, Liguria,"
            " Sardegna (isola) e, dal 1848, nei territori progressivamente annessi.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, 'avanti di me Ufficiale dello Stato Civile del"
            " Comune di...', nome dell'ufficiale (di norma il Sindaco o un consigliere delegato).\n"
            "- Formula di apertura formale e burocratica: 'Il sottoscritto Ufficiale dello Stato"
            " Civile...' o 'Noi sottoscritto...'.\n"
            "- Comparente: il padre; nome, cognome, età, professione, domicilio.\n"
            "- Neonato: sesso, nome, data e ora di nascita; 'figlio legittimo di'.\n"
            "- Padre e madre: dati completi.\n"
            "- Due testimoni con dati completi.\n"
            "- Formula di chiusura e firme.\n"
            "\nPARTICOLARITÀ DELL'AREA SABAUDA:\n"
            "- Alcuni atti sono in FRANCESE o bilingui italiano/francese (Savoia, Valle d'Aosta,"
            " Nizza fino al 1860): trascrivili nella lingua d'origine senza tradurre.\n"
            "- L'anno è in cifre arabiche.\n"
            "- Linguaggio molto burocratico e standardizzato.\n"
            "- Eventuale citazione di 'art. X del Codice Civile Albertino'.\n"
            "- Il modello albertino 1848-1865 è il precursore diretto del SCI.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Se il testo è in francese, trascrivilo in francese senza tradurre.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Piemonte — Atto di Matrimonio (1837-1865)": (
            "\nTIPOLOGIA: Atto di matrimonio del Regno di Sardegna — Codice Albertino"
            " (SCR/Piemonte, 1837-1865).\n"
            "Il matrimonio civile è separato dal canonico. Il Codice Albertino richiedeva"
            " la preventiva pubblicazione dei bandi e il consenso parentale per i minorenni\n"
            "(uomini sotto 25 anni, donne sotto 21).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Ufficiale dello Stato Civile.\n"
            "- Dichiarazione delle pubblicazioni (bandi): date e luoghi.\n"
            "- Sposo: nome, cognome, età, professione, domicilio, stato civile, padre e madre"
            " (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile della madre.\n"
            "- Consensi parentali (atto separato richiamato) o dispense.\n"
            "- Dichiarazione di volontà di ciascuno sposo.\n"
            "- DUE testimoni (a differenza del SCI che ne richiedeva quattro).\n"
            "- Formula di proclamazione dell'ufficiale e firme.\n"
            "\nPARTICOLARITÀ:\n"
            "- Possibile redazione in francese o bilingue: trascrivere nella lingua d'origine.\n"
            "- Eventuale riferimento al numero atto di nascita degli sposi.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Se il testo è in francese, trascrivilo in francese senza tradurre.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Piemonte — Atto di Morte (1837-1865)": (
            "\nTIPOLOGIA: Atto di morte del Regno di Sardegna — Codice Albertino"
            " (SCR/Piemonte, 1837-1865).\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: anno, data, comune, Ufficiale dello Stato Civile.\n"
            "- Due dichiaranti con dati anagrafici e relazione col defunto.\n"
            "- Defunto: nome, cognome, età, professione, domicilio, stato civile, nome del coniuge"
            " (cognome da nubile per le donne), nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora e luogo del decesso.\n"
            "- Causa di morte: terminologia medica relativamente moderna rispetto agli altri SCR"
            " (influenza del modello piemontese-francese); in alcune zone ancora terminologia popolare.\n"
            "  Es.: 'polmonite', 'febbre tifoide', 'colera morbus', 'congestione cerebrale'.\n"
            "- Firme o croci dei dichiaranti, firma dell'ufficiale.\n"
            "\nPARTICOLARITÀ:\n"
            "- Possibile redazione in francese o bilingue (Savoia, Nizza): trascrivere nella"
            " lingua d'origine.\n"
            "- Linguaggio burocratico standardizzato.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Se il testo è in francese, trascrivilo in francese senza tradurre.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCR/Veneto (Lombardo-Veneto / Impero austriaco, 1816-1866) ────────
        "SCR/Veneto — Atto di Nascita (1816-1866)": (
            "\nTIPOLOGIA: Atto di nascita del Lombardo-Veneto sotto dominazione austriaca (1816-1866).\n"
            "Redatto in italiano (talvolta con intestazioni in tedesco) secondo il modello del\n"
            "Codice Civile Austriaco (ABGB). Sostituisce i registri napoleonici SCN dopo il 1815.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: distretto, comune, anno, N° atto, nome dell'i.r. (imperiale-regio) funzionario.\n"
            "- Data e luogo della nascita.\n"
            "- Sesso del neonato e nome imposto.\n"
            "- Padre: nome, cognome, professione, domicilio, religione.\n"
            "- Madre: nome, cognome da nubile, religione.\n"
            "- Due testimoni: nome, cognome, professione, domicilio.\n"
            "- Firme o croci dei presenti, firma del funzionario.\n"
            "\nPARTICOLARITÀ REGIONALI:\n"
            "- Venezia e province venete: redatto in italiano con formula napoleonica adattata.\n"
            "- Trento e zone bilingue: possibile presenza di intestazioni in tedesco o latino;\n"
            "  trascrivere nella lingua in cui è scritto, senza tradurre.\n"
            "- Il funzionario può avere il titolo 'i.r. Delegato', 'i.r. Commissario distrettuale',\n"
            "  'Podestà': trascrivi il titolo per intero.\n"
            "- Abbreviazione 'i.r.' = <imperial-regio>; scioglila se usata in forma abbreviata.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Nomi di battesimo spesso in forma latinizzata o germanizzata: trascrivi come scritti.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Veneto — Atto di Matrimonio (1816-1866)": (
            "\nTIPOLOGIA: Atto di matrimonio del Lombardo-Veneto / Impero austriaco (1816-1866).\n"
            "Redatto dall'i.r. funzionario civile dopo la celebrazione religiosa (matrimonio concordatario)\n"
            "o contestualmente ad essa in alcune aree.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: distretto, comune, anno, N° atto, funzionario.\n"
            "- Sposo: nome, cognome, età o data di nascita, luogo di nascita, professione, domicilio,\n"
            "  stato civile (celibe/vedovo), religione, nome e cognome del padre e della madre.\n"
            "- Sposa: stesse informazioni; cognome da nubile.\n"
            "- Eventuali atti preliminari citati: pubblicazioni (banns), nulla osta, dispense.\n"
            "- Testimoni (di norma quattro): nome, cognome, età, professione, domicilio.\n"
            "- Firma o croce degli sposi, dei testimoni, del funzionario.\n"
            "\nPARTICOLARITÀ:\n"
            "- Il consenso dei genitori è richiesto per i minori: spesso citato con nome e firma.\n"
            "- 'Figlio/a di fu...' = padre o madre defunti: trascrivi 'fu' letteralmente.\n"
            "- Possibili intestazioni bilingui (italiano/tedesco): trascrivi entrambe le versioni.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCR/Veneto — Atto di Morte (1816-1866)": (
            "\nTIPOLOGIA: Atto di morte del Lombardo-Veneto / Impero austriaco (1816-1866).\n"
            "Redatto dal funzionario i.r. civile su denuncia dei familiari o vicini.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: distretto, comune, anno, N° atto, funzionario.\n"
            "- Dichiaranti (uno o due): nome, cognome, professione, domicilio, relazione col defunto.\n"
            "- Defunto: nome, cognome, età, professione, domicilio, stato civile, religione.\n"
            "- Nome del coniuge (per vedovi/vedove: cognome da nubile per le donne).\n"
            "- Nomi dei genitori (con 'fu' se defunti).\n"
            "- Data, ora e luogo del decesso.\n"
            "- Causa di morte: spesso in latino o in terminologia medica d'epoca; frequenti\n"
            "  'febris', 'convulsiones', 'apoplexia', 'colera morbus', 'vaiolo'.\n"
            "- Firme o croci dei dichiaranti, firma del funzionario.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Causa di morte: non correggere, trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        # ── SCI: Stato Civile Italiano (dal 1° gennaio 1866) ──────────────────
        "SCI — Atto di Nascita (dal 1866)": (
            "\nTIPOLOGIA: Atto di nascita dello Stato Civile Italiano (SCI, R.D. 15/11/1865,"
            " in vigore dal 1/1/1866).\n"
            "Formato standardizzato e prestampato, redatto dall'ufficiale di stato civile comunale.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione prestampata: N° atto (nell'intestazione), anno, comune, ufficiale.\n"
            "- Formula fissa: 'L'anno milleottocento..., addì... del mese di..., avanti di me...'\n"
            "- Dichiarante: il padre o un altro comparente; nome, cognome, età, professione, domicilio.\n"
            "- Nascita: luogo esatto (via, casa), data e ora, sesso del neonato ('di sesso maschile/femminile').\n"
            "- Nome imposto al neonato.\n"
            "- Madre: nome, cognome (da nubile), età, professione, domicilio.\n"
            "- Padre: nome, cognome, età, professione, domicilio.\n"
            "- Due testimoni maschi maggiorenni: nome, cognome, età, professione, domicilio.\n"
            "- Formula di chiusura e firme: dichiarante, testimoni, ufficiale.\n"
            "- Dal 1875: possibili annotazioni a margine (matrimoni futuri, morte, note).\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il N° atto è in cifre arabiche: trascrivilo con precisione.\n"
            "- Le date dell'anno sono in lettere; giorno e mese possono essere in cifre o lettere.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA (frequenti nel SCI): trascrivi tutte le annotazioni a margine"
            " con il tag [MARGINE: ...]; contengono spesso riferimenti a matrimonio, morte,"
            " riconoscimento di paternità — informazioni preziose.\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCI — Atto di Matrimonio (dal 1866)": (
            "\nTIPOLOGIA: Atto di matrimonio dello Stato Civile Italiano (SCI, dal 1/1/1866).\n"
            "Formato standardizzato prestampato. Nel SCI il matrimonio comprende tre fasi documentali:\n"
            "1) Pubblicazioni (richiesta preventiva, tre domeniche consecutive);\n"
            "2) Atto di matrimonio vero e proprio;\n"
            "3) Eventuali allegati (estratti di nascita, consensi, dispense).\n"
            "\nSTRUTTURA DELL'ATTO DI MATRIMONIO:\n"
            "- Intestazione: N° atto, anno, comune, ufficiale di stato civile.\n"
            "- Formula fissa: 'L'anno... avanti di me... si sono presentati...'\n"
            "- Sposo: nome, cognome, luogo e data di nascita (o età), professione, domicilio,"
            " stato civile (celibe/vedovo), nome del padre e della madre (con 'fu' se defunti).\n"
            "- Sposa: stesse informazioni; cognome da nubile della madre.\n"
            "- Dichiarazione delle pubblicazioni: date e luoghi delle tre pubblicazioni.\n"
            "- Consensi dei genitori se minorenni, o nulla osta se maggiorenni.\n"
            "- Dichiarazione di volontà: formula 'Dichiaro di voler...'; risposta dell'altro sposo.\n"
            "- Proclamazione dell'ufficiale.\n"
            "- Quattro testimoni: nome, cognome, età, professione, domicilio.\n"
            "- Firme degli sposi, dei testimoni, dell'ufficiale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il N° atto è in cifre arabiche: trascrivilo con precisione.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "SCI — Atto di Morte (dal 1866)": (
            "\nTIPOLOGIA: Atto di morte dello Stato Civile Italiano (SCI, dal 1/1/1866).\n"
            "Formato standardizzato prestampato, redatto dall'ufficiale di stato civile comunale.\n"
            "\nSTRUTTURA DELL'ATTO:\n"
            "- Intestazione: N° atto, anno, comune, ufficiale di stato civile.\n"
            "- Formula fissa: 'L'anno... avanti di me... si sono presentati...'\n"
            "- Due dichiaranti: nome, cognome, età, professione, domicilio e relazione col defunto.\n"
            "- Defunto: nome, cognome, luogo e data di nascita (o età), professione, domicilio,"
            " stato civile (celibe/coniugato/vedovo).\n"
            "  Se coniugato o vedovo: nome e cognome del coniuge (con 'fu' se defunto).\n"
            "  Nomi del padre e della madre del defunto (con 'fu' se defunti).\n"
            "- Data, ora e luogo esatto del decesso.\n"
            "- Causa di morte: se indicata, può usare terminologia medica ottocentesca.\n"
            "- Firme dei dichiaranti (o nota di analfabetismo), firma dell'ufficiale.\n"
            "- Dal 1875: possibili annotazioni a margine.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il N° atto è in cifre arabiche: trascrivilo con precisione.\n"
            "- 'Fu' indica genitore o coniuge defunto: trascrivi letteralmente.\n"
            "- Cause di morte arcaiche comuni: 'apoplessia', 'idropisia', 'consunzione',"
            " 'febbre perniciosa', 'mal sottile' (tisi/tubercolosi) — trascrivile esattamente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),

        "Atto di Stato Civile (Nascita / Battesimo)": (
            "\nTIPOLOGIA: Atto di nascita o battesimo (XIX secolo, registro civile o parrocchiale,"
            " periodo non specificato).\n"
            "- Campi chiave: nome del neonato, genitori (padre e madre con cognome da nubile),"
            " data e luogo di nascita, testimoni, ufficiale o parroco.\n"
            "- I nomi di persona sono spesso abbreviati (Gio. = Giovanni, Batta. = Battista, Fran.co = Francesco).\n"
            "- Il termine 'fu' indica genitore defunto (es. 'figlio di Giovanni fu Isidoro'): trascrivilo letteralmente.\n"
            "- Le date sono in lettere: 'il giorno tre maggio milleottocentosei'.\n"
            "- MARGINALIA: trascrivi qualsiasi annotazione a margine separandola con il tag [MARGINE: ...].\n"
            "- Per cognomi dialettali con variante fonetica plausibile, aggiungi la variante subito dopo"
            " tra parentesi quadre: es. Bortolato [Bortolotti].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con la riga '--- ATTO N ---'"
            " (dove N è il numero progressivo), prima di ogni atto incluso il primo.\n"
        ),
        "Atto di Stato Civile (Matrimonio)": (
            "\nTIPOLOGIA: Atto di matrimonio (XIX secolo, registro civile o parrocchiale).\n"
            "- Campi chiave: sposo e sposa (nome, cognome, età, professione, domicilio),"
            " padri e madri di entrambi (con 'fu' se defunti), testimoni.\n"
            "- Il termine 'fu' indica genitore defunto: trascrivilo letteralmente.\n"
            "- Frequenti formule latine come 'in facie Ecclesiae' nei registri parrocchiali.\n"
            "- MARGINALIA: trascrivi annotazioni a margine (spesso rimandano a successive nascite o morti)"
            " separandole con il tag [MARGINE: ...].\n"
            "- Per cognomi dialettali con variante fonetica plausibile, aggiungi la variante tra parentesi"
            " quadre: es. Mancuso [Mancusa].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con la riga '--- ATTO N ---'"
            " (dove N è il numero progressivo), prima di ogni atto incluso il primo.\n"
        ),
        "Atto di Stato Civile (Morte / Sepoltura)": (
            "\nTIPOLOGIA: Atto di morte o sepoltura (XIX secolo).\n"
            "- Campi chiave: nome e cognome del defunto, età, causa di morte (se indicata),"
            " data e luogo del decesso, dichiaranti, sepoltura.\n"
            "- Il termine 'fu' indica genitore defunto: trascrivilo letteralmente.\n"
            "- Presta attenzione ai termini medici arcaici per le cause di morte.\n"
            "- MARGINALIA: trascrivi annotazioni a margine separandole con il tag [MARGINE: ...].\n"
            "- Per cognomi con variante fonetica plausibile (defunto, dichiaranti o testimoni),"
            " aggiungi la variante tra parentesi quadre: es. Ricci [Rizzi].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con la riga '--- ATTO N ---'"
            " (dove N è il numero progressivo), prima di ogni atto incluso il primo.\n"
        ),
        "Processetto / Allegati Matrimoniali": (
            "\nTIPOLOGIA: Processetto matrimoniale o allegati (documenti istruttori pre-matrimonio).\n"
            "Il processetto include: interrogatori degli sposi e dei testimoni, estratti di battesimo,"
            " estratti di morte dei genitori defunti, eventuali dispense.\n"
            "- Identifica e trascrivi le singole sezioni: intestazione dell'ufficio,"
            " domande del cancelliere, risposte dei comparenti, sottoscrizioni e sigilli.\n"
            "- I comparenti indicano spesso 'figlio/a di ... fu ...' (genitore defunto):"
            " trascrivi 'fu' letteralmente.\n"
            "- Le deposizioni testimoniali iniziano tipicamente con formule come"
            " 'Comparso avanti di me...' o 'Il sottoscritto dichiara...'.\n"
            "- Le dispense papali o vescovili hanno intestazioni in latino: trascrivile integralmente.\n"
            "- Ogni documento all'interno del fascicolo va separato con una riga vuota e il tag"
            " [DOCUMENTO N:] come intestazione.\n"
            "- MARGINALIA: trascrivi annotazioni a margine separandole con il tag [MARGINE: ...].\n"
            "- Se un singolo foglio contiene più deposizioni o atti distinti, separa ciascuno con"
            " '--- ATTO N ---' prima di ogni sezione.\n"
        ),
        "Pubblicazioni di Matrimonio (registro bandi)": (
            "\nTIPOLOGIA: Registro delle Pubblicazioni di Matrimonio (bandi).\n"
            "Registro autonomo tenuto dall'ufficiale di stato civile (SC) o dal parroco (registro\n"
            "parrocchiale), distinto dall'atto di matrimonio vero e proprio. Ogni bando elenca la\n"
            "coppia e viene ripetuto per tre domeniche/giorni festivi consecutivi.\n"
            "\nSTRUTTURA TIPICA (varia tra SC e parrocchiale):\n"
            "- Intestazione di pagina: anno, comune o parrocchia, ufficiale o parroco.\n"
            "- Per OGNI pubblicazione:\n"
            "  * N° della pubblicazione (progressivo annuale).\n"
            "  * Data della prima, seconda e terza pubblicazione.\n"
            "  * Sposo: nome, cognome, età o data di nascita, professione, domicilio,\n"
            "    stato civile (celibe/vedovo), nome del padre e della madre (con 'fu' se defunti).\n"
            "  * Sposa: stesse informazioni; cognome da nubile.\n"
            "  * Eventuali opposizioni ricevute: trascrivi per intero.\n"
            "  * Esito: 'Nessuna opposizione' / 'Opposizione da parte di...' / 'Dispensato'.\n"
            "- Firma dell'ufficiale o del parroco.\n"
            "\nVARIANTI:\n"
            "- SCN (1806-1815): tre pubblicazioni obbligatorie nei giorni festivi;\n"
            "  formula molto standard.\n"
            "- SCR/SCI: stessa struttura con varianti locali (date domenicali).\n"
            "- Registro parrocchiale: formula in latino ('facta prima / secunda / tertia\n"
            "  proclamatione die...') o in italiano; eventuali note di dispensa vescovile.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Se la pagina contiene PIÙ DI UNA PUBBLICAZIONE, separa ciascuna con\n"
            "  '--- PUBBLICAZIONE N ---'.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- MARGINALIA (frequenti: opposizioni tardive, annotazioni di avvenuto matrimonio):\n"
            "  trascrivi con il tag [MARGINE: ...].\n"
        ),

        # ── Registri Parrocchiali (Concilio di Trento, sec. XVI-XIX) ──────────────
        "Registro Parrocchiale — Battesimi (sec. XVI-XIX)": (
            "\nTIPOLOGIA: Registro parrocchiale dei battesimi (Tridentino, sec. XVI-XIX).\n"
            "Istituito per decreto del Concilio di Trento (Sess. XXIV, 1563). Per l'Italia\n"
            "pre-napoleonica è la FONTE PRIMARIA di nascita; in Lombardo-Veneto e Stato\n"
            "Pontificio rimane tale fino al 1865.\n"
            "\nSTRUTTURA (varia per epoca e area geografica):\n"
            "- Registri più antichi (sec. XVI-XVII): spesso una riga per battesimo, testo\n"
            "  narrativo in latino o latino/volgare; colonne non sempre presenti.\n"
            "- Registri del sec. XVIII: struttura più codificata; alcune diocesi adottano\n"
            "  modelli a colonne (data | cognome-nome | padre | madre | padrini | celebrante).\n"
            "- Registri del sec. XIX (post-1800): spesso pre-stampati a colonne; struttura\n"
            "  simile al SCN per i soli dati anagrafici.\n"
            "\nELEMENTI PRINCIPALI DA RICONOSCERE:\n"
            "- Data del battesimo (e, se indicata, data di nascita separata).\n"
            "- Nome battesimale imposto.\n"
            "- Padre: nome, cognome, professione ('agricoltore', 'artigiano', titolo).\n"
            "- Madre: nome e cognome da nubile.\n"
            "- Padrino e madrina (patrinus / patrina): spesso figure chiave per reti sociali;\n"
            "  trascrivi nome, cognome e, se indicata, professione o relazione.\n"
            "- Ministro celebrante: nome e titolo del sacerdote.\n"
            "- 'Figlio legittimo di' / 'figlio naturale di' / 'esposto' (trovatello): annota.\n"
            "- Eventuali note di supplimento o abbreviazioni del battesimo in pericolo di vita\n"
            "  ('in cassum' o 'sub conditione'): trascrivi per intero.\n"
            "\nABBREVIAZIONI FREQUENTI (sciogli tra < >):\n"
            "- fil. leg. = <filius/filia legitimus/a>\n"
            "- fil. ill. / fil. nat. = <filius/filia illegitimus/a / naturalis>\n"
            "- q.m / qm / qu. / quond. = <quondam> (padre/avo defunto)\n"
            "- 7bris/7bre = <Septembris/Septembre>; 8bris = <Octobris>; 9bris = <Novembris>;\n"
            "  Xbris/Xbre = <Decembris/Decembre>.\n"
            "- Kal. = <Kalendas>; Id. = <Idus>; Non. = <Nonas> (date romane).\n"
            "- Pat. / Patr. = <Patrinus>; Mat. / Matr. = <Matrina>.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il testo può essere in LATINO, in volgare italiano o misto: trascrivilo nella\n"
            "  lingua originale senza tradurre.\n"
            "- La grafia varia notevolmente per epoca: cancelleresca umanistica (sec. XVI-XVII),\n"
            "  barocca (sec. XVII-XVIII), corsiva italiana moderna (sec. XIX).\n"
            "- Nomi in forma latinizzata: 'Joannes' = Giovanni, 'Franciscus' = Francesco,\n"
            "  'Bartholomaeus' = Bartolomeo; TRASCRIVILI nella forma latina come appaiono.\n"
            "- 'quondam' (q.m) indica genitore defunto: trascrivilo letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni a margine con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO/RIGA, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "Registro Parrocchiale — Matrimoni (sec. XVI-XIX)": (
            "\nTIPOLOGIA: Registro parrocchiale dei matrimoni (Tridentino, sec. XVI-XIX).\n"
            "Istituito dal Concilio di Trento (Sess. XXIV, 1563). Il matrimonio canonico\n"
            "ha valore civile per tutta l'età moderna in Italia (fino al SCN/SCR).\n"
            "\nSTRUTTURA (varia per epoca):\n"
            "- Sec. XVI-XVII: testo narrativo in latino; il sacerdote descrive la celebrazione.\n"
            "- Sec. XVIII: struttura più codificata; alcune diocesi adottano moduli a colonne.\n"
            "- Sec. XIX (aree senza stato civile laico): struttura quasi-civile, spesso pre-stampata.\n"
            "\nELEMENTI PRINCIPALI DA RICONOSCERE:\n"
            "- Data della celebrazione; chiesa e parrocchia.\n"
            "- Sposo: nome, cognome, condizione/professione, parrocchia di origine, padre e madre\n"
            "  (con quondam/q.m se defunti), stato civile (celibe / vedovo).\n"
            "- Sposa: stesse informazioni; cognome da nubile.\n"
            "- Tre pubblicazioni (banni): date delle tre domeniche; spesso indicate con 'factis\n"
            "  tribus proclamationibus die...' o formule simili.\n"
            "- Eventuali DISPENSE (da consanguinità, affinità, impedimenti): citate con\n"
            "  riferimento all'autorità (vescovo, papa) e data; trascrivile per intero.\n"
            "- Due o quattro testimoni con dati anagrafici.\n"
            "- Sacerdote celebrante: nome, titolo, parrocchia.\n"
            "- Formula di consenso: in latino 'Ego vos in matrimonium coniungo' o simili.\n"
            "\nABBREVIAZIONI FREQUENTI (sciogli tra < >):\n"
            "- q.m / qm / qu. / quond. = <quondam>\n"
            "- 7bris / 8bris / 9bris / Xbris = <Septembris / Octobris / Novembris / Decembris>\n"
            "- vid. / vid.ua = <viduo / vidua> (vedovo/vedova)\n"
            "- coel. / coeleb. = <coelebs> (celibe)\n"
            "- disp. = <dispensatio>\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Testo in latino, in volgare o misto: trascrivi nella lingua originale senza tradurre.\n"
            "- Nomi latinizzati: trascrivi nella forma latina come appaiono.\n"
            "- 'quondam' indica genitore defunto: trascrivilo letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "Registro Parrocchiale — Morti / Sepolture (sec. XVI-XIX)": (
            "\nTIPOLOGIA: Registro parrocchiale dei morti e delle sepolture (Tridentino, sec. XVI-XIX).\n"
            "Il registro dei morti fu reso obbligatorio dal Rituale Romanum (1614); molte parrocchie\n"
            "lo anticiparono dopo Trento. È la fonte primaria di morte per l'Italia pre-napoleonica.\n"
            "\nSTRUTTURA (varia per epoca e diocesi):\n"
            "- Sec. XVI-XVII: spesso un semplice elenco narrativo ('die X obiit N.N. aetatis\n"
            "  annorum X, sepultus in ecclesia...').\n"
            "- Sec. XVIII: struttura più articolata; alcune diocesi adottano colonne.\n"
            "- Sec. XIX: spesso pre-stampato a colonne; include data, nome, età, causa, sepoltura.\n"
            "\nELEMENTI PRINCIPALI DA RICONOSCERE:\n"
            "- Data del decesso e/o della sepoltura (possono essere distinte).\n"
            "- Defunto: nome, cognome, età (spesso approssimata: 'circiter annos X'),\n"
            "  professione, condizione (coniugato, vedovo, celibe, nubile).\n"
            "- Genitori: nome del padre e della madre (con quondam se defunti).\n"
            "- Coniuge superstite (se vedovo/vedova): nome e cognome.\n"
            "- Sacramenti ricevuti: 'munitus omnibus sacramentis', 'sine sacramentis',\n"
            "  'subito obitus': trascrivili per intero, non abbreviare.\n"
            "- Luogo di sepoltura: chiesa, altare, cappella, camposanto; spesso indicato\n"
            "  con 'sepultus/a in...' o 'tumulatus/a in...'.\n"
            "- Causa di morte: terminologia arcaica, latina o dialettale; frequenti:\n"
            "  'febris', 'hydrops', 'apoplexia', 'phthisis', 'vaiuolo', 'mal di petto',\n"
            "  'convulsioni', 'senio' (vecchiaia). Non correggere, trascrivi letteralmente.\n"
            "- Celebrante / parroco che esegue la sepoltura.\n"
            "\nABBREVIAZIONI FREQUENTI (sciogli tra < >):\n"
            "- q.m / qm / qu. = <quondam>\n"
            "- an. circ. / circiter an. = <annorum circiter> (età approssimativa)\n"
            "- mun. sacr. = <munitus/a sacramentis>\n"
            "- sep. / sepult. = <sepultus/a>\n"
            "- 7bris / 8bris / 9bris / Xbris = <Septembris / Octobris / Novembris / Decembris>\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Testo in latino, in volgare o misto: trascrivi nella lingua originale senza tradurre.\n"
            "- L'età è spesso indicata in forma approssimativa: 'circiter annos 40',\n"
            "  'di anni circa 50': trascrivi esattamente come scritto.\n"
            "- Cause di morte arcaiche: non correggere, non modernizzare.\n"
            "- 'quondam' indica genitore defunto: trascrivilo letteralmente.\n"
            "- MARGINALIA: trascrivi annotazioni con il tag [MARGINE: ...].\n"
            "- Se la pagina contiene PIÙ DI UN ATTO, separa ciascuno con '--- ATTO N ---'.\n"
        ),
        "Registro degli Esposti / Nati Illegittimi": (
            "\nTIPOLOGIA: Registro degli esposti (trovatelli) o dei nati illegittimi.\n"
            "Tenuto dall'Orfanotrofio, dall'Ospedale degli Innocenti, dalla Ruota o dalla parrocchia;\n"
            "in epoca SCI (dal 1866) l'atto è redatto dall'ufficiale di stato civile.\n"
            "Fonte primaria per ricerche su figli illegittimi, bambini abbandonati, adozioni storiche.\n"
            "\nTIPOLOGIE PRINCIPALI:\n"
            "  A) REGISTRO DELL'ISTITUTO (Ospedale degli Innocenti, Pio Luogo, Ruota, ecc.):\n"
            "     - N° di ingresso progressivo.\n"
            "     - Data e ora del ritrovamento o della consegna.\n"
            "     - Luogo di ritrovamento (scalino, ruota, porta della chiesa, strada).\n"
            "     - Segni distintivi portati dal bambino: fasce, biglietti, monete spezzate, nastri,\n"
            "       medaglie: trascrivi per intero ogni oggetto o nota allegata.\n"
            "     - Sesso e nome imposto dall'istituto.\n"
            "     - Balia o famiglia affidataria: nome, cognome, comune.\n"
            "     - Eventuali annotazioni successive: riconoscimento da parte dei genitori naturali,\n"
            "       morte, matrimonio, uscita dall'istituto.\n"
            "  B) ATTO SCI DI NASCITA DI FIGLIO ILLEGITTIMO (dal 1866):\n"
            "     - Struttura analoga all'atto di nascita SCI standard.\n"
            "     - Padre: 'padre ignoto' o 'non dichiarato'; oppure nome se riconoscimento volontario.\n"
            "     - Madre: nome o 'madre che vuole rimanere anonima'; se dichiarata, cognome da nubile.\n"
            "     - MARGINALIA fondamentale: possibili riconoscimenti posticipati ('il padre X\n"
            "       riconosce il figlio in data...'); trascrivi con [MARGINE: ...].\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Biglietti e note allegati al trovatello: trascrivi tra virgolette, lettera per lettera,\n"
            "  anche se frammentari o dialettali.\n"
            "- Nomi imposti dall'istituto: spesso santi del giorno, cognomi inventati (es. 'Colombo',\n"
            "  'Innocenti', 'Diotallevi', 'Esposito'): trascrivi come scritti.\n"
            "- 'Figlio/a di N.N.' = genitore ignoto: trascrivi letteralmente.\n"
            "- Separa ogni scheda / atto con '--- ESPOSTO N ---'.\n"
            "- MARGINALIA: trascrivi tutte le annotazioni con il tag [MARGINE: ...].\n"
        ),

        "Stati delle Anime Granducato di Toscana": (
            "\nTIPOLOGIA: Stato delle Anime del Granducato di Toscana"
            " (formato codificato dalle Sovrane Disposizioni — Biglietto della R. Segreteria di Stato 12 novembre 1840).\n"
            "\nSTRUTTURA DELLE COLONNE (FISSA PER LEGGE — leggi TUTTE le colonne per ogni riga):\n"
            "  Col.1  = N° Casa\n"
            "  Col.2  = N° Famiglia\n"
            "  Col.3  = N° Progressivo Persona\n"
            "  Col.4  = Cognome\n"
            "  Col.5  = Nome\n"
            "  Col.6  = Età\n"
            "  Col.7  = Stato civile Maschio: Celibe (barrare)\n"
            "  Col.8  = Stato civile Maschio: Ammogliato (barrare)\n"
            "  Col.9  = Stato civile Maschio: Vedovo (barrare)\n"
            "  Col.10 = Stato civile Femmina: Nubile (barrare)\n"
            "  Col.11 = Stato civile Femmina: Maritata (barrare)\n"
            "  Col.12 = Stato civile Femmina: Vedova (barrare)\n"
            "  Col.14 = Religione\n"
            "  Col.15 = Patria (luogo di origine)\n"
            "  Col.16 = Professione\n"
            "  Col.19 = Osservazioni\n"
            "\nREGOLE OBBLIGATORIE PER LA TRASCRIZIONE A TABELLA:\n"
            "- Trascrivi OGNI riga come una riga di testo con i valori separati da ' | ',"
            " nell'ordine: N°Casa | N°Fam | Prog | Cognome | Nome | Età | Celibe | Ammogliato | Vedovo"
            " | Nubile | Maritata | Vedova | Religione | Patria | Professione | Osservazioni\n"
            "- Inizia con una riga di intestazione con i nomi delle colonne separati da ' | '.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore precedente in quella colonna:\n"
            "  TRASCRIVILI come \" senza espanderli.\n"
            "- Le colonne stato civile (7–12) contengono un segno grafico (croce, tratto, X) o sono vuote:\n"
            "  trascrivi '1' se barrata, '' se vuota.\n"
            "- REGOLA GENERE — LE COLONNE COMANDANO SUL NOME: il segno nelle caselle stato civile è"
            " un dato fisico certo. PROCEDURA: (1) conta le 6 caselle nell'ordine"
            " Celibe | Ammogliato | Vedovo | Nubile | Maritata | Vedova;"
            " (2) se il segno è nella posizione 1, 2 o 3 → persona MASCHIO;"
            " se nella posizione 4, 5 o 6 → persona FEMMINA;"
            " (3) solo DOPO aver stabilito il genere dalle caselle, verifica il nome:"
            " se il nome letto non corrisponde al genere (es. nome in -a per un maschio),"
            " correggi il nome al genere indicato dalle caselle"
            " (es. 'Angelina' → 'Angelino', 'Giuseppa' → 'Giuseppe', 'Giovanna' → 'Giovanni')."
            " Le caselle prevalgono SEMPRE sul nome, mai il contrario.\n"
            "- NON saltare righe: anche le righe con soli segni ditto vanno trascritte.\n"
            "- Se una colonna è vuota scrivi uno spazio tra i separatori: | |\n"
            "- Se un valore è illeggibile usa [?].\n"
            "- TRASCRIVI NOMI E COGNOMI ESATTAMENTE come scritti: non correggere, non normalizzare.\n"
            "- N°CASA E N°FAMIGLIA NELLE RIGHE DI CONTINUAZIONE: per le persone che non sono"
            " capofamiglia, le colonne N°Casa (col.1) e N°Famiglia (col.2) sono BLANK (vuote);"
            " il numero progressivo crescente si trova SEMPRE nella terza colonna (N°Progressivo)."
            " NON scrivere il progressivo in col.2.\n"
            "  ESEMPIO riga capofamiglia:  1 | 1 | 1 | Acciaj | Gaspero | 60 |  | 1 |  |  |  |  | ...\n"
            "  ESEMPIO riga continuazione: |  | 2 | \" | Rosa | 62 |  |  |  |  | 1 |  | ...\n"
            "- RIGHE PER PAGINA: il modello imposto dal Biglietto 1840 prevede ESATTAMENTE 25 righe"
            " dati per pagina (da progressivo 1 a 25, o continuazione del progressivo del fascicolo)."
            " Nelle pagine intermedie ci sono sempre 25 righe; solo l'ultima pagina del registro può"
            " averne meno. Se vedi righe vuote fino a 25, trascrivile come righe vuote (tutti | |)."
            " Non inventare righe oltre quelle realmente presenti nell'immagine.\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
            "- ETÀ A DUE CIFRE: l'età è un numero intero scritto in cifre arabiche (1-3 cifre)."
            " Leggi TUTTE le cifre: non trascrivere '4' se nel registro è scritto '40',"
            " né '2' se è '22', né '1' se è '18', né '4' se è '44'."
            " Le decine e le unità sono scritte ravvicinate in corsivo: scorri tutta la casella."
            " CIFRE COMUNI IN CORSIVO TOSCANO 1840: '3' e '9' si distinguono per il gambo inferiore"
            " (il '3' è aperto, il '9' ha una coda chiusa); '1' e '2' sono cifre singole brevi;"
            " '11', '22', '33', '44' hanno entrambe le cifre — non leggerne solo una."
            " In caso di dubbio usa [?] dopo l'età ma trascrivi comunque entrambe le cifre viste.\n"
            "- MOGLIE DEL CAPOFAMIGLIA: la prima persona femmina registrata dopo un capofamiglia"
            " con col.8 (Ammogliato) barrata è SEMPRE sua moglie → Maritata (col.11 barrata)."
            " Le figlie nubili vengono elencate DOPO la moglie. Non confondere moglie con figlia."
            " Se una donna adulta (età > 15) segue immediatamente un Ammogliato nello stesso nucleo,"
            " verificare sempre che la casella col.11 sia barrata nell'immagine.\n"
            "- COGNOMI E NOMI — FEDELTÀ ASSOLUTA: trascrivi ogni cognome e nome ESATTAMENTE"
            " come scritto nel documento, lettera per lettera. Non correggere, non normalizzare:"
            " 'Luisa' rimane 'Luisa' (non 'Luigia'),"
            " 'Angelo' rimane 'Angelo' (non 'Angiolo'), 'Santi' rimane 'Santi' (non 'Sante'),"
            " 'Angelino' rimane 'Angelino' (non 'Angiolino'), 'Andrei' rimane 'Andrei' (non 'Andreini').\n"
            "- ABBREVIAZIONI NEI NOMI: NON usare mai le parentesi angolate < > per i nomi propri"
            " di persona. I nomi di persona vanno trascritti SEMPRE per intero."
            " Le parentesi angolate < > sono riservate alle abbreviazioni di termini comuni (es. titoli,"
            " professioni, formule), MAI per nomi o cognomi. Scrivi 'Bernardo' non 'Bernard<o>',"
            " 'Giovanni' non 'Giov<anni>', 'Caterina' non 'Cat<erina>'.\n"
            "- GENDER RULE — BAMBINI PICCOLI: per bambini di età 0-3 anni la grafia corsiva del nome"
            " può essere ambigua. PROCEDURA: (1) conta la casella barrata per il genere"
            " (caselle 1-3=maschio/Celibe, caselle 4-6=femmina/Nubile); (2) trascrivi il nome"
            " ESATTAMENTE come scritto nel documento, qualunque esso sia."
            " NON correggere un nome femminile in maschile o viceversa basandoti sulle caselle:"
            " un bambino di 1 anno può chiamarsi 'Tina' (femmina, Nubile) o 'Pietro' (maschio, Celibe)."
            " Le caselle determinano la colonna stato civile, NON il nome."
            " Se il nome è illeggibile scrivi [?].\n"
            "- COLONNE STATO CIVILE FEMMINILE: col.10=Nubile, col.11=Maritata, col.12=Vedova."
            " Conta rigorosamente le 6 caselle stato civile da sinistra: Celibe(7)|Ammogliato(8)|Vedovo(9)|Nubile(10)|Maritata(11)|Vedova(12)."
            " Non confondere col.10 con col.11: una croce nella quarta casella = Nubile, nella quinta = Maritata.\n"
            "- CAPOFAMIGLIA AMMOGLIATO: quando una riga capofamiglia ha col.8=1 (Ammogliato),"
            " significa che è sposato. La sua colonna stato civile è la SECONDA delle sei caselle."
            " Non confondere con Celibe (prima casella). Es.: `4 | 4 | 13 | Bargelli | Pietro | 42 |  | 1 |  |  |  |  | ...`"
            " — il '1' è nella seconda posizione = Ammogliato, non Celibe.\n"
            "- REGOLA ETÀ-STATO CIVILE (vincolo assoluto): un individuo con età ≤ 14 anni NON PUÒ"
            " essere Ammogliato (col.8), Maritata (col.11), Vedovo (col.9) o Vedova (col.12)."
            " Per ogni persona con età ≤ 14, la colonna barrata è OBBLIGATORIAMENTE"
            " Celibe (col.7, maschio) o Nubile (col.10, femmina)."
            " Se la lettura ti suggerisce un'altra colonna per un under-15, hai contato male le caselle:"
            " riconsidera la posizione del segno con questa certezza come vincolo.\n"
            "- VERIFICA COERENZA NUCLEO FAMILIARE: dopo aver trascritto tutte le righe di un nucleo,"
            " controlla: (a) se il capofamiglia ha Ammogliato=1, nel nucleo DEVE comparire esattamente"
            " una donna con Maritata=1 (la moglie). Se non trovi nessuna Maritata, hai attribuito"
            " Nubile (col.10) invece di Maritata (col.11) alla moglie — rileggi la sua riga."
            " (b) se il capofamiglia ha Celibe=1 o Vedovo=1, non ci sono Maritate nel nucleo"
            " (a meno di figli già sposati conviventi, raro in questa tipologia).\n"
            "- COGNOMI DIFFICILI: alcuni cognomi in corsivo toscano hanno lettere molto simili:"
            " 'Bargelli' (con doppia 'l' e finale 'i') non è 'Bargilli';"
            " 'Bertoni' (con 'o') non è 'Bertini' (con 'i')."
            " In caso di dubbio tra 'e'/'i' o 'o'/'i' in un cognome, trascrivi esattamente"
            " le lettere che vedi senza modificare, e aggiungi [?] solo se veramente illeggibile.\n"
            "- NEONATI (età 0-1): un bambino di 1 anno può essere maschio (Celibe, col.7) O femmina"
            " (Nubile, col.10). Leggi PRIMA la casella per determinare il genere,"
            " poi trascrivi il NOME ESATTAMENTE come scritto: 'Tina' è un nome femminile valido"
            " (Nubile), 'Pietro' è maschile (Celibe). NON sovrascrivere mai il nome letto.\n"
        ),
        # ── Anagrafe asburgica Lombardo-Veneto (sec. XIX) ───────────────────
        "Anagrafe / Censimento Lombardo-Veneto (sec. XIX)": (
            "\nTIPOLOGIA: Anagrafe asburgica del Lombardo-Veneto (sec. XIX, circa 1816-1865).\n"
            "Il sistema asburgico imponeva una rilevazione anagrafica periodica (Seelenbeschreibung\n"
            "o Coscrizione / Descrizione delle anime) strutturata a colonne fisse per decreto\n"
            "imperiale. Applicata in Lombardia, Veneto, Friuli, Trentino.\n"
            "\nSTRUTTURA DELLE COLONNE (fissa per decreto, ma con varianti locali):\n"
            "  Col.1  = N\u00b0 d'ordine della casa (numero civico asburgico)\n"
            "  Col.2  = N\u00b0 della famiglia nella casa\n"
            "  Col.3  = N\u00b0 progressivo della persona nella famiglia\n"
            "  Col.4  = Cognome\n"
            "  Col.5  = Nome (e nome del santo patrono, se indicato)\n"
            "  Col.6  = Anno di nascita (NON l'et\u00e0: trascrivere l'anno, es. '1804')\n"
            "  Col.7  = Luogo di nascita / Comune\n"
            "  Col.8  = Sesso (M / F)\n"
            "  Col.9  = Stato civile (celibe/ammogliato/vedovo o nubile/maritata/vedova)\n"
            "  Col.10 = Relazione col capofamiglia (capofamiglia, moglie, figlio, ecc.)\n"
            "  Col.11 = Religione (quasi sempre 'Cat.' o 'R.C.' = romano-cattolica)\n"
            "  Col.12 = Professione / condizione\n"
            "  Col.13 = Coscrizione militare (maschi: leva / esente / militare in servizio)\n"
            "  Col.14 = Osservazioni / note\n"
            "\nNOTA: il numero di colonne e la loro denominazione pu\u00f2 variare per anno e\n"
            "  distretto. Leggi le intestazioni del documento e adattati.\n"
            "\nREGOLE OBBLIGATORIE PER LA TRASCRIZIONE A TABELLA:\n"
            "- Trascrivi OGNI riga come riga di testo con valori separati da ' | ',\n"
            "  nell'ordine delle colonne stampate sul registro.\n"
            "- Inizia con una riga di intestazione con i nomi delle colonne separati da ' | '.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore precedente in quella colonna:\n"
            "  TRASCRIVILI come \" senza espanderli.\n"
            "- Anno di nascita: trascrivilo come numero (es. '1832'), NON come età.\n"
            "- Il CAPOFAMIGLIA (Hausvater / capofamiglia) è la prima riga della famiglia:\n"
            "  la relazione nella colonna 10 è 'capofamiglia' o lasciata vuota.\n"
            "- Relazioni col capofamiglia comuni: moglie, figlio, figlia, genero, nuora,\n"
            "  nipote, servitore, garzone: trascrivile esattamente come appaiono.\n"
            "- Coscrizione militare (col.13): valori tipici: 'atto', 'esente', 'in servizio',\n"
            "  'riformato'; per le donne la colonna è spesso vuota o barrata.\n"
            "- NON saltare righe: anche quelle con soli segni ditto vanno trascritte.\n"
            "- Se una colonna è vuota scrivi uno spazio tra i separatori: | |\n"
            "- Se un valore è illeggibile usa [?].\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),\n"
            "  le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile\n"
            "  come riga continua unita da ' | ', non come due righe separate.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- I cognomi possono essere in forma dialettale veneta, lombarda o friulana:\n"
            "  non correggere, trascrivi esattamente.\n"
            "- Termini tedeschi o latinizzati possono comparire nelle colonne Professione\n"
            "  e Osservazioni: trascrivi nella lingua originale.\n"
            "- Abbreviazioni: 'Cat.' = <Cattolico/a>; 'R.C.' = <Romano Cattolico/a>;\n"
            "  'vid.' = <vedovo/vedova>; 'cell.' = <celibe/nubile>.\n"
        ),
        "Stato delle Anime / Censimento Parrocchiale": (
            "\nTIPOLOGIA: Stato delle Anime o censimento parrocchiale (TABELLA MULTI-COLONNA).\n"
            "\nSTRUTTURA ATTESA DELLE COLONNE (leggi TUTTE le colonne per ogni riga):\n"
            "  Col.1 = N° d'ordine Casa | Col.2 = N° Famiglia | Col.3 = N° Persona\n"
            "  Col.4 = Cognome | Col.5 = Nome | Col.6 = Età | Col.7 = Stato civile\n"
            "  Col.8 = Religione/Patria | Col.9 = Professione | Col.10 = Osservazioni\n"
            "\nREGOLE OBBLIGATORIE PER LA TRASCRIZIONE A TABELLA:\n"
            "- Trascrivi OGNI riga come una riga di testo con i valori separati da ' | '.\n"
            "  Esempio: 1 | 1 | 1 | Davini | Enrico | 45 | M | Poncarale | Contadino |\n"
            "- Inizia con una riga di intestazione con i nomi delle colonne separati da ' | '.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore precedente in quella colonna:\n"
            "  TRASCRIVILI come \" senza espanderli.\n"
            "- NON saltare righe: anche le righe con soli segni ditto vanno trascritte.\n"
            "- Se una colonna è vuota scrivi uno spazio tra i separatori: | |\n"
            "- Se un valore è illeggibile usa [?].\n"
            "- NON aggiungere note o commenti: solo la tabella.\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
        ),
        "Censimento Storico (Generico)": (
            "\nTIPOLOGIA: Censimento storico (es. censimento statale 1861, 1871, 1881, 1901).\n"
            "- La struttura è tabellare: trascrivi ogni riga con i valori separati da ' | '.\n"
            "- Inizia con una riga di intestazione riportando i nomi delle colonne come indicati nel documento.\n"
            "- Colonne tipiche: N° ordine | Cognome e Nome | Relazione col capofamiglia"
            " | Sesso | Anno di nascita | Stato civile | Professione | Istruzione | Note.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore soprastante:"
            " TRASCRIVILI come \" senza espanderli.\n"
            "- NON saltare righe vuote o con soli segni ditto.\n"
            "- Se un valore è illeggibile usa [?].\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
        ),
        "Catasto Onciario (Due Sicilie, sec. XVIII)": (
            "\nTIPOLOGIA: Catasto Onciario del Regno delle Due Sicilie (sec. XVIII, 1740-1753 ca.).\n"
            "Strumento fiscale borbonico che censisce ogni 'fuoco' (nucleo familiare/unità produttiva)\n"
            "di ogni comune del Regno. Fonte primaria per la genealogia meridionale pre-stato civile.\n"
            "\nSTRUTTURA DEL DOCUMENTO:\n"
            "Il catasto onciario è suddiviso in sezioni per categoria di contribuente:\n"
            "  1. FUOCHI DESCRITTI (cittadini ordinari): capofamiglia, famiglia, beni.\n"
            "  2. FUOCHI FRANCHI O PRIVILEGIATI (clero, nobili, vedove, orfani).\n"
            "  3. UNIVERSITÀ (beni comuni del paese).\n"
            "  4. FUOCHI FORESTIERI (proprietari non residenti).\n"
            "\nPER OGNI FUOCO / NUCLEO FAMILIARE trascrivi:\n"
            "  [INTESTAZIONE FUOCO]\n"
            "  - N° del fuoco (progressivo) e nome del capofamiglia (con titolo: 'Don', 'mastro', ecc.).\n"
            "  - Professione / mestiere del capofamiglia.\n"
            "  - Età dichiarata (spesso arrotondata al quinquennio).\n"
            "  [COMPONENTI FAMIGLIA]\n"
            "  - Moglie: nome, età.\n"
            "  - Figli: nome, sesso, età.\n"
            "  - Altri conviventi: relazione, nome, età.\n"
            "  [BENI DICHIARATI]\n"
            "  - Beni stabili (terre, case, botteghe): descrizione, estensione, ubicazione, valore in once.\n"
            "  - Industria (attività artigianale/commerciale): descrizione e reddito annuo in grana/once.\n"
            "  - Capitali a credito (censi, prestiti): creditore/debitore, somma, interesse.\n"
            "  [ONCIATURA]\n"
            "  - Totale imponibile in once, tarì e grana (es. '12 once, 3 tarì, 10 grana').\n"
            "  - Deduzioni (moglie, figli, debiti): elenca con valori.\n"
            "  - Netto tassabile finale.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- La grafia è corsiva napoletana (sec. XVIII): frequenti abbreviazioni;\n"
            "  scioglile con <> (es. 'on.' = <once>, 'gr.' = <grana>, 'tt.' = <tarì>).\n"
            "- 'Fu' indica genitore/marito defunto: trascrivi letteralmente.\n"
            "- 'Vedova di...' o 'pupillo/a di fu...' sono frequenti per fuochi franchi.\n"
            "- Unità di misura locali per le terre: 'tomolo', 'moggio', 'versura', 'canna';\n"
            "  trascrivi letteralmente senza convertire.\n"
            "- Separa ogni fuoco con '--- FUOCO N ---'.\n"
            "- MARGINALIA: trascrivi con [MARGINE: ...].\n"
        ),
        "Catasto Gregoriano (Stato Pontificio, 1816-1835)": (
            "\nTIPOLOGIA: Catasto Gregoriano dello Stato Pontificio (1816-1835).\n"
            "Rilievo fondiario istituito da Pio VII con Motu Proprio del 1816 e completato sotto\n"
            "Gregorio XVI. Copre Lazio, Marche, Umbria, Romagna e Legazioni. Fonte primaria per\n"
            "genealogia pre-SC dell'Italia centrale pontificia.\n"
            "\nSTRUTTURA DEL CATASTO GREGORIANO:\n"
            "Il Catasto Gregoriano è composto da diverse serie documentali:\n"
            "  1. MAPPE (planimetrie): non testuali; trascrivere solo le didascalie e i numeri di\n"
            "     particella eventualmente leggibili.\n"
            "  2. BROGLIARDI (registri descrittivi delle particelle):\n"
            "     - N° di particella (corrisponde alla mappa).\n"
            "     - Proprietario: nome, cognome, professione, comune di residenza.\n"
            "     - Qualità del suono (uso del suolo): 'seminativo', 'vignato', 'olivato', 'prato',\n"
            "       'bosco', 'casa colonica', 'casa di abitazione', ecc.\n"
            "     - Posizione: contrada, confini (nord/sud/est/ovest con nome del confinante).\n"
            "     - Estensione in rubbi, scorzi, quartucci (unità pontificie); trascrivi senza convertire.\n"
            "     - Rendita imponibile (in scudi romani).\n"
            "  3. SOMMARIONI (registro per proprietario):\n"
            "     - Nome del proprietario.\n"
            "     - Elenco delle particelle possedute con superficie e rendita totale.\n"
            "  4. TAVOLE INDICATIVE (elenchi per contrada).\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Grafia corsiva italiana del sec. XIX; abbreviazioni frequenti:\n"
            "  'sem.' = <seminativo>; 'vig.' = <vignato>; 'ol.' = <olivato>; 'sc.' = <scudi>;\n"
            "  'r.' / 'rub.' = <rubbi>; 'sc.' e 'sorz.' = <scorzi>.\n"
            "- Trascrivi i numeri di particella con precisione (sono il collegamento con la mappa).\n"
            "- Nomi dei proprietari: possono includere titoli nobiliari o ecclesiastici\n"
            "  ('Principe', 'Marchese', 'Reverendo', 'Convento di...'); trascrivi per intero.\n"
            "- Confini: 'a tramontana' = nord; 'a mezzogiorno' = sud; 'a levante' = est;\n"
            "  'a ponente' = ovest: trascrivi come scritti, non convertire.\n"
            "- Separa ogni scheda di particella con '--- PARTICELLA N ---'.\n"
            "- Per i Sommarioni, separa ogni proprietario con '--- PROPRIETARIO: nome ---'.\n"
            "- MARGINALIA: trascrivi con [MARGINE: ...].\n"
        ),

        # ── Leva Militare (1865-1940) ────────────────────────────────────────────
        "Ruolo di Matricola / Leva Militare (1865-1940)": (
            "\nTIPOLOGIA: Ruolo di Matricola della Leva Militare (1865-1940).\n"
            "Registro tabellare annuale redatto dal Distretto Militare per classe di nascita.\n"
            "Ogni pagina elenca pi\u00f9 coscritti in righe; le colonne sono prestampate e fisse per legge.\n"
            "\nSTRUTTURA DELLE COLONNE (dal modello ministeriale):\n"
            "  Col.1  = N\u00b0 di matricola (progressivo del ruolo)\n"
            "  Col.2  = Cognome\n"
            "  Col.3  = Nome (e nome del padre)\n"
            "  Col.4  = Data di nascita (giorno, mese, anno)\n"
            "  Col.5  = Comune e provincia di nascita\n"
            "  Col.6  = Professione al momento della leva\n"
            "  Col.7  = Istruzione (sa leggere/scrivere / analfabeta)\n"
            "  Col.8  = Statura in cm (es. '1m 68' o '168')\n"
            "  Col.9  = Capelli (colore e forma: 'castani lisci', 'neri ricci', ecc.)\n"
            "  Col.10 = Occhi (colore: 'castani', 'azzurri', 'grigi')\n"
            "  Col.11 = Colorito (incarnato: 'sano', 'pallido', 'bruno')\n"
            "  Col.12 = Segni particolari (cicatrici, nei, difetti fisici; spesso 'nessuno')\n"
            "  Col.13 = Vaccinazioni (vaccinato / rivaccinato / non vaccinato)\n"
            "  Col.14 = Stato civile (celibe / ammogliato)\n"
            "  Col.15 = Decisione della commissione (abile / riformato / rimandato / esente)\n"
            "  Col.16 = Corpo / reggimento assegnato\n"
            "  Col.17 = Note e annotazioni (numerose: congedi, richiami, decorazioni, diserzione)\n"
            "\nREGOLE OBBLIGATORIE PER LA TRASCRIZIONE A TABELLA:\n"
            "- Trascrivi OGNI riga coscritto con valori separati da ' | ', nell'ordine delle colonne.\n"
            "- Inizia con una riga di intestazione con i nomi delle colonne separati da ' | '.\n"
            "- I segni ditto (\") o 'idem' indicano ripetizione del valore precedente: TRASCRIVILI\n"
            "  come \" senza espanderli.\n"
            "- NON saltare righe: anche quelle con soli segni ditto vanno trascritte.\n"
            "- Se una colonna è vuota scrivi uno spazio tra i separatori: | |\n"
            "- Se un valore è illeggibile usa [?].\n"
            "\nCAMPI CRITICI:\n"
            "- Statura: trascrivila in cm esatti ('168' o '1.68'); non arrotondare.\n"
            "- Connotati fisici (capelli, occhi, colorito, segni): trascrivi la descrizione\n"
            "  letteralmente, anche se apparentemente banale ('nessuno segno').\n"
            "- Col.15 Decisione: valori tipici: 'abile', 'riformato' (con causa: es. 'riformato\n"
            "  per miopia'), 'rimandato all'anno...', 'esente', 'dispensato'.\n"
            "- Col.17 Note: campo molto variabile, spesso con abbreviazioni militari:\n"
            "  'C.A.' = <Corpo d'Armata>; 'Regg.' = <Reggimento>; 'Brig.' = <Brigata>;\n"
            "  's.f.' o 'senza famiglia' = <senza fissa dimora>; '\u00e8 morto' con data.\n"
            "- MARGINALIA: trascrivi annotazioni a margine con il tag [MARGINE: ...].\n"
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),\n"
            "  le colonne di sinistra e destra formano una riga continua: trascrivile unite da ' | '.\n"
        ),
        "Foglio Matricolare (scheda individuale, 1865-1940)": (
            "\nTIPOLOGIA: Foglio Matricolare individuale (1865-1940).\n"
            "Documento pre-stampato di una o due pagine, dedicato a un singolo coscritto.\n"
            "Non è un elenco tabellare: è una scheda con campi fissi e spazi da riempire a mano.\n"
            "\nSTRUTTURA DELLA SCHEDA (ordine tipico):\n"
            "SEZIONE ANAGRAFICA:\n"
            "- N\u00b0 di matricola | Classe (anno di nascita)\n"
            "- Cognome e Nome | Nome del padre | Nome della madre\n"
            "- Data e luogo di nascita | Comune e provincia | Mandamento\n"
            "- Professione | Istruzione (sa leggere/scrivere)\n"
            "SEZIONE CONNOTATI FISICI:\n"
            "- Statura in cm | Capelli | Occhi | Colorito | Segni particolari\n"
            "- Vaccinazioni\n"
            "SEZIONE DECISIONE DI LEVA:\n"
            "- Anno e luogo della visita di leva\n"
            "- Decisione (abile / riformato / rimandato): con eventuale causa medica\n"
            "- Corpo e reggimento assegnato\n"
            "SEZIONE SERVIZIO MILITARE (annotazioni cronologiche):\n"
            "- Chiamata alle armi, incorporazione, fermate, congedi, richiami\n"
            "- Promozioni, decorazioni, punizioni\n"
            "- Data e causa di congedo definitivo o morte\n"
            "SEZIONE NOTE:\n"
            "- Spesso contiene aggiornamenti postumi: matrimonio, figli, cambio residenza, morte\n"
            "\nREGOLE PER LA TRASCRIZIONE:\n"
            "- NON usare il formato tabellare a ' | ': trascrivi i campi come coppie\n"
            "  'NomeCampo: Valore' su righe separate, rispettando la struttura del documento.\n"
            "- Separa le sezioni della scheda con una riga vuota e il nome della sezione\n"
            "  tra parentesi quadre: [SEZIONE ANAGRAFICA], [CONNOTATI], [DECISIONE LEVA], ecc.\n"
            "- Trascrivi TUTTI i campi, anche quelli vuoti: es. 'Segni particolari: nessuno'.\n"
            "- Abbreviazioni militari frequenti (sciogli tra < >):\n"
            "  c.a. = <congedo assoluto>; c.i. = <congedo illimitato>; r.t.e. = <in attesa>;\n"
            "  d.a. = <dispensa d'arma>; Regg. = <Reggimento>; Comp. = <Compagnia>;\n"
            "  Batt. = <Battaglione>; C.A. = <Corpo d'Armata>; D.M. = <Distretto Militare>.\n"
            "- Le date militari sono in formato gg/mm/aaaa o gg mese aaaa: trascrivile esattamente.\n"
            "- MARGINALIA: trascrivi annotazioni a margine con il tag [MARGINE: ...].\n"
            "- Se il documento comprende due pagine, trascrivile in sequenza senza interruzione.\n"
        ),

        # ── Emigrazione e documenti di viaggio (sec. XIX-XX) ──────────────────
        "Passaporto / Permesso di Espatrio (sec. XIX-XX)": (
            "\nTIPOLOGIA: Passaporto o permesso di espatrio italiano (sec. XIX-XX).\n"
            "Documento individuale (o familiare) rilasciato dalla Prefettura o dal Comune\n"
            "per consentire l'espatrio o il viaggio all'estero. Fonte primaria per genealogia\n"
            "della diaspora italiana (emigrazione verso Americhe, Australia, Europa).\n"
            "\nPERIODI E FORMATI:\n"
            "  - Sec. XIX (pre-1870): passaporto manoscritto o stampato parzialmente;\n"
            "    intestazione del regno (Sardegna, Due Sicilie, Toscana, ecc.).\n"
            "  - 1870-1900: passaporto del Regno d'Italia unito; connotati fisici descrittivi.\n"
            "  - 1901-1940: modulo standard con foto (dal ~1912); include rubriche fisse.\n"
            "  - Nulla osta / permesso di emigrazione: formato ministeriale (Commissariato\n"
            "    Generale dell'Emigrazione, dal 1901); include porto di imbarco e destinazione.\n"
            "\nELEMENTI DA RICONOSCERE E TRASCRIVERE:\n"
            "  [INTESTAZIONE]\n"
            "  - Autorità rilasciante (Prefettura di..., Podestà di..., R. Consolato di...).\n"
            "  - N° del passaporto o del registro.\n"
            "  - Data di rilascio e scadenza.\n"
            "  [TITOLARE]\n"
            "  - Nome, cognome, data e luogo di nascita.\n"
            "  - Professione.\n"
            "  - Domicilio / residenza.\n"
            "  - Stato civile; se sposato: nome del coniuge.\n"
            "  - Nome del padre e della madre.\n"
            "  [CONNOTATI FISICI] (cruciali per identificazione)\n"
            "  - Statura, capelli, occhi, colorito, segni particolari.\n"
            "  - Trascrivi ogni connotato letteralmente.\n"
            "  [ACCOMPAGNATORI / FAMILIARI] (se presenti sul documento)\n"
            "  - Nome, relazione, età di ogni accompagnatore (moglie, figli).\n"
            "  [DESTINAZIONE]\n"
            "  - Paese / città di destinazione.\n"
            "  - Porto di imbarco (es. Genova, Napoli, Palermo).\n"
            "  - Durata del permesso.\n"
            "  [VISTI E TIMBRI]\n"
            "  - Trascrivi testi di visti consolari, timbri leggibili, date di rinnovo.\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Connotati fisici: trascrivi ogni termine esattamente (anche 'nessuno segno').\n"
            "- Timbri e visti in lingue straniere (francese, inglese, spagnolo, portoghese):\n"
            "  trascrivi nella lingua originale senza tradurre.\n"
            "- MARGINALIA: trascrivi con [MARGINE: ...].\n"
        ),
        "Atti Consolari Italiani all'Estero": (
            "\nTIPOLOGIA: Atti consolari italiani all'estero (nascita, matrimonio, morte, cittadinanza).\n"
            "Redatti dai Consolati e Ambasciate del Regno d'Italia (poi Repubblica Italiana)\n"
            "per cittadini italiani residenti o transitanti all'estero. Depositati anche in Italia\n"
            "nei Comuni di iscrizione e all'Archivio di Stato tramite il Ministero degli Esteri.\n"
            "Fonte fondamentale per la diaspora italiana (Americhe, Australia, Nord Africa, Europa).\n"
            "\nTIPOLOGIE PRINCIPALI:\n"
            "  A) ATTO DI NASCITA CONSOLARE:\n"
            "     - Struttura analoga all'atto SCI; intestazione: 'Consolato Generale d'Italia\n"
            "       in [città], [paese]'.\n"
            "     - Spesso redatto in italiano anche in paesi di lingua diversa.\n"
            "     - Include paese e città di nascita (all'estero); eventuale nome locale.\n"
            "  B) ATTO DI MATRIMONIO CONSOLARE:\n"
            "     - Matrimonio celebrato davanti al Console; riconoscimento del matrimonio civile\n"
            "       italiano anche all'estero.\n"
            "     - Include luogo di nascita degli sposi (spesso in Italia) e comune di iscrizione.\n"
            "  C) ATTO DI MORTE CONSOLARE:\n"
            "     - Include luogo e causa di morte all'estero.\n"
            "     - Informazioni sull'eventuale rimpatrio della salma o sepoltura locale.\n"
            "  D) DICHIARAZIONE / ATTO DI CITTADINANZA:\n"
            "     - Rinnovo o conservazione della cittadinanza italiana; rinuncia.\n"
            "  E) ANNOTAZIONI SU ATTI COMUNALI ITALIANI:\n"
            "     - Se il documento è un'annotazione (trascrizione/margine) su un atto italiano,\n"
            "       segnalalo con [ANNOTAZIONE CONSOLARE: ...].\n"
            "\nREGOLE PALEOGRAFICHE:\n"
            "- Il documento è prevalentemente in italiano, ma può contenere parti in lingua locale;\n"
            "  trascrivi ogni parte nella lingua originale senza tradurre.\n"
            "- Nomi stranieri: trascrivi nella grafia del documento, poi la variante italiana\n"
            "  (se presente) tra parentesi quadre: es. 'Giovanni [John]'.\n"
            "- 'Fu' indica genitore defunto: trascrivi letteralmente.\n"
            "- Timbri consolari, numeri di protocollo, date di spedizione: trascrivi per intero.\n"
            "- MARGINALIA: trascrivi con [MARGINE: ...].\n"
            "- Separa atti multipli con '--- ATTO N ---'.\n"
        ),

        "Documento Notarile": (
            "\nTIPOLOGIA: Documento notarile (contratto, testamento, atto di compravendita, ecc.).\n"
            "- Formula di apertura tipica: 'In Dei nomine amen...' o 'Regnante...'\n"
            "- Presta attenzione ai nomi delle parti contraenti, testimoni, notaio rogante.\n"
            "- Le abbreviazioni dei titoli (Ser, Dominus, fu = quondam) sono frequenti.\n"
            "- Conserva le formule legali anche se apparentemente ridondanti.\n"
            "- Il termine 'fu' equivale al latino 'quondam': trascrivilo letteralmente.\n"
            "- Per cognomi con variante grafica (es. forme latinizzate o dialettali),"
            " aggiungi la variante tra parentesi quadre: es. De Marchi [de Marchis].\n"
        ),
        "Atto in Latino Ecclesiastico": (
            "\nTIPOLOGIA: Atto ecclesiastico in latino (registro parrocchiale pre-napoleonico,"
            " dispensa, atto sinodale, necrologio, ecc.).\n"
            "- Trascrivi il testo in latino esattamente come scritto, senza tradurre.\n"
            "- Le abbreviazioni latine sono frequentissime: sciogli quelle ovvie"
            " tra parentesi angolate < >. Es: Xbris = <Decembris>, 7bris = <Septembris>,"
            " Joannis = <Johannis>, fil. = <filius/filia>, ux. = <uxor>.\n"
            "- Il 'fu' si esprime in latino come 'quondam' (qm, q.m): trascrivilo letteralmente.\n"
            "- Le date usano lo stile romano (Kalendas, Nonas, Idus) o l'anno ab Incarnatione:"
            " trascrivile come appaiono.\n"
            "- Mantieni la struttura del documento: formula di apertura, corpo, sottoscrizioni,"
            " sigilli o croci notarili.\n"
            "- MARGINALIA: trascrivi annotazioni a margine separandole con il tag [MARGINE: ...].\n"
        ),
        "Lettera / Corrispondenza Privata": (
            "\nTIPOLOGIA: Lettera o corrispondenza privata.\n"
            "- Mantieni l'intestazione (luogo, data) e la formula di chiusura.\n"
            "- La grafia privata è spesso corsiva e irregolare: privilegia la lettura letterale.\n"
            "- Non correggere errori ortografici o grammaticali dello scrivente.\n"
        ),
        "Testo a Stampa Antico": (
            "\nTIPOLOGIA: Testo a stampa antico (incunabolo, cinquecentina, ecc.).\n"
            "- Distingui la 's' lunga (ſ) dalla 'f' moderna.\n"
            "- Mantieni le varianti grafiche arcaiche (ex → et, & → e, œ, æ).\n"
            "- Segnala le interruzioni di pagina con [PAGINA NUOVA].\n"
        ),
        "Indice / Registro degli Atti": (
            "\nTIPOLOGIA: Indice o sommario di registro storico (indice degli atti di nascita, matrimonio,"
            " morte, o altro registro civile/parrocchiale).\n"
            "- La struttura è tabellare o a elenco: trascrivi fedelmente ogni riga.\n"
            "- Colonne tipiche: N° atto | Cognome e Nome | Data | Pagina/Foglio | Note.\n"
            "- Usa ' | ' come separatore di colonna; includi una riga di intestazione con i nomi"
            " delle colonne come indicati nel registro.\n"
            "- Trascrivi i cognomi esattamente come scritti, senza normalizzare.\n"
            "- I numeri di atto o di pagina/foglio sono riferimenti critici: trascrivili con"
            " massima precisione.\n"
            "- Se l'indice è su più colonne affiancate (es. due colonne per A–M e N–Z),"
            " trascrivile come due blocchi separati da una riga vuota, ognuno con la propria intestazione.\n"
            '- I segni ditto (") o \'idem\' indicano cognome uguale alla riga precedente:'
            ' TRASCRIVILI come " senza espanderli.\n'
            "- DOPPIA PAGINA: se l'immagine mostra due pagine affiancate (foglio aperto),"
            " le colonne di sinistra e di destra formano insieme un'unica riga: trascrivile come"
            " riga continua unita da ' | ', non come due righe separate.\n"
        ),
        "Documento Generico / Non Classificato": (
            "\nTIPOLOGIA: Documento non classificato (nessuna tipologia predefinita applicabile).\n"
            "- Trascrivi il testo esattamente come appare, preservando la struttura visiva originale.\n"
            "- Se il documento ha colonne o tabelle, usa ' | ' come separatore di colonna.\n"
            "- Se il documento ha sezioni distinte (titoli, paragrafi, firme), separale con una riga vuota.\n"
            "- Segnala con [MARGINE: ...] qualsiasi annotazione a margine o fuori dal corpo principale.\n"
        ),
    }

    specific = type_specific.get(doc_type, type_specific["Documento Generico / Non Classificato"])

    prompt = base + specific

    if example_text.strip():
        prompt += (
            "\n\n--- TRASCRIZIONE DI RIFERIMENTO ---\n"
            "La seguente trascrizione è di una pagina dello stesso documento.\n"
            "Usala per imparare la calligrafia e il vocabolario specifico dello scrivano:\n\n"
            f"{example_text.strip()}\n"
            "--- FINE RIFERIMENTO ---\n"
        )

    if user_instructions.strip():
        prompt += f"\n\n--- ISTRUZIONI AGGIUNTIVE ---\n{user_instructions.strip()}\n"

    prompt += "\n\nINIZIA ORA LA TRASCRIZIONE:"
    return prompt
